/* eslint-disable */
_w['_sydBaseSpecifierPrefix'] = 'rms-answers-SharedStaticAssets-';
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'uquopt,osbsdrecoff,memmidlat,fluxcopilot,fdwtlst,fluxprod',
  enableNoToneOpt: true,
  sydCrtOpts: 'memdefadcst2',
  sydPrcOpts: 'memdefadcst2',
  voiceSrOptions: 'cdxrwss,cdxsydoroff,cdxwsnnc,lidprimary',
  sydIDs: 'ecvfcf,ntbkcf,dlid,autotts,sydoroff,voicemap,cmcallapptf,vnextvoice,tts5,abv1logf,bgstream,mlchatardg,edgenorrwrap,tstchtadd,sydtransjson,styleovr,sugchip2,0212boptpsc,111mem,0115fluxcp,116langwbs0,0112wtlst,118wcsmws0,bingfccf,1119backos,1pgptwdes,0105xapclis0,124multi2ts0,14bicfluxv2s0',
  sydBaseUrl: location.origin,
  compSydRequestSource: 'cib',
  compSydRequestScenario: 'chat',
  enableCustomStylingForMsgExtensions: true,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enablePLSingleColumnStylesV2: true,
  enableCheckMsbCibBundleLoad: true,
  enableSapphireSydVoiceExp: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'Chinese (China)',
  userMailId: randomString(Math.round(Math.random()*16))+'@'+randomLowercaseString(randomString(Math.round(Math.random()*12)))+'.com',
  username: randomString(Math.round(Math.random()*16)),
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSpeechContinuousErrorHandling: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableSydImageCreate: true,
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableNewTopicAutoExpand: true,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
// 设置已登录账号的聊天对话次数
  maxTurnsPerConversation: 30,
// 设置未登录账号的聊天对话次数
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  maxMessageLengthBalanced: 2000,
  maxMessageLengthCreative: 4000,
  maxMessageLengthPrecise: 4000,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableE2EPerf: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableJWTFTRFix: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForBalancedTone: true,
  enableStreamSyntheticTextResponsesForCreativeTone: true,
  enableStreamSyntheticTextResponsesForPreciseTone: true,
  syntheticStreamSpeed: 55,
  syntheticStreamSpeedForBalancedTone: 55,
  syntheticStreamSpeedForCreativeTone: 55,
  syntheticStreamSpeedForPreciseTone: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableCodeBarV2: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  sydSapphireUpsellVisualSearchQRCodeUrl: 'https://bingapp.microsoft.com/bing?adjust=13uz7blz_13evwnmy',
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing&adjust=euhmno2_oy62nz1',
  enableConvModeSwitchAjax: true,
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enableAutosuggestMetrics: true,
  enablePrivacyConsent: true,
  enableFixCodeXAsBug: true,
  enableChatQueryClickable: true,
  enableThreads: true,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableDynamicShareTitle: true,
  enableSharePreview: true,
  enableSharedHoverCitations: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableFixOnReplaceAllJSError: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  eifpiab: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableTableBarFlatActions: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableBotMessageActionsBar: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableDelayGetChats: true,
  enableExportDocxWithFormat: true,
  enableExportDocxWithTableFormat: true,
  enableThreadSync: true,
  enableFlux3P: true,
  f3pMsaAccountOnly: true,
  disableWelcomeScreen: true,
  enableWelcomeScreenV2: true,
  codexTableVersion: true,
  enableBICHistory: true,
  enableAIPersonasForDesktop: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  enableCitationsOnSentences: true,
  enableAnswerCards: true,
  fileUploadMaxSizeLongContext: 10000000,
  fileUploadMaxAudioSize: 15000000,
  fileUploadFileNameLengthLimitation: 100,
  fileMaxCountForGptCreator: 5,
  fileMaxCountForChat: true,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableFaviconsV2: true,
  enableFaviconChatCopilotIcon: true,
  enableUserIpAddress: true,
  enableNewChatIconInActionBar: true,
  enableActionBarV2: true,
  speechSurface: 'desktop',
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: true,
  enableUpdateUserMessageId: true,
  enablePluginPanelFre: true,
  enableMobileFirstClickShare: true,
  enableInlinePersonalizationConsent: true,
  enableSydWelcomeScreenMobileEvents: true,
  personalizationInlineConsentTurn: true,
  enableNoBingSearchResponseBackground: true,
  enableNoSearchPluginMetaMessage: true,
  enableShareInThreadsHeader: true,
  enableThreadsConsent: true,
  enableDeleteSingleConversationMemory: true,
  enableStableAutosuggestion: true,
  threadsAutoSaveOptionset: 'autosave',
  enableThreadContextMenuV2: true,
  enableBCBSensitivityLabel: true,
  enableOneDs: true,
  enablePromptHandling: true,
  dedicatedIpType: 'unknown',
  enableCiqAttachmentsOnInputChanges: true,
  enableSpeechAutoDetectLanguage: true,
  enableCachedContentFixForIsStartOfSession: true,
  extraNotebookOptionsSets: 'blocklist,prjupy',
  notebookMaxMessageLength: 18000,
  initialShowConvPresent: true,
  enableAttributionsV2: true,
  minimumZeroInputSuggestionCount: true,
  enableCopilotLayout: true,
  enableSpeechLogNoiseReduction: true,
  enableAltVoiceQuerySubmissionOnMobileABV2: true,
  multimediaSearchFormCode: 'IACMIR',
  multimediaSearchEnableMediaCanvas: true,
  multimediaSearchMaxImageCount: 3,
  enableSuggestionChipDisplayText: true,
  defaultFallBackSERPQuery: 'Bing AI',
  enableRelativeSignInUrl: true,
  enableChatScrollFix: true,
  enableBopCustomGreeting: true,
  enableSwiftKeyLatestUX1: true,
  enablePluginChatModeOnly: true,
  enableGhostingSuggestTelemetry: true,
  bceTermsOfUseVersion: 2,
  disableTitlePreviewLabel: true,
  enableFreeSydney: true,
  enableDesignerGPT: true,
  defaultMaxPersonaCount: 6,
  isBingUserSignedIn: true,
  freeSydneyCopilotIconUrl: '/rp/_WT61VllAyx4fyquJgufM7hwmeg.png',
  freeSydneySydneyIconUrl: '/rp/ZIFQVh6WX4QKgPWuBMBKNrERh3A.png',
  freeSydneyDesignerIconUrl: '/rp/l8iFubC9EgDGvKo7xeNIvSQwikU.png',
  enableF3pNoSearchBgFix: true,
  enableFaqBcc: true,
  enableFaqBce: true,
  faqBccBceUrl: '/new',
  gptCreatorCopilotCreatorPath: '/turing/copilot/creator',
  gptCreatorBingPreviewPath: '/search',
  gptCreatorSharePath: '/search',
  enableStreamingInBackground: true,
  enableCitationSuperscriptFix: true,
  enableGptCreatorConfigurePanelKnowledges: true,
  enableGptCreatorConfigurePanelcapabilities: true,
  enableGptCreatorConfigurePanelImageGenerator: true,
  freeSydneyOptionSets: [{
    value: 'fluxsydney'
  }],
  neuripsOptionSets: [{
    value: 'nipsgpt'
  }],
  autoHideConvInterval: 600000,
  enableAjaxBundlePLoad: true,
  PLoadIID: 'SERP.5805'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  letsChat: 'Lets chat',
  pause: 'Pause',
  play: 'Start the game',
  loading: 'Loading',
  stop: 'Stop',
  canceling: 'Canceling',
  more: 'More',
  expand: 'Expand',
  seeMore: 'See more',
  seeLess: 'See less',
  seeChatHistory: 'See chat history',
  hideChatHistory: 'Hide chat history',
  seeMoreGPTs: 'See more Copilot GPT',
  seeLessGPTs: 'See less Copilot GPT',
  raiSuggestions: 'Show more suggestions',
  raiSuggestionsClose: 'Hide suggestions',
  close: 'Close',
  refresh: 'Refresh',
  next: 'Next',
  cancel: 'Cancel',
  preview: 'Preview',
  of: 'of',
  submit: 'Submit',
  explore: 'Explore',
  exploreMore: 'Explore more',
  startOver: 'Start again',
  responses: 'Responses',
  readAloud: 'Read aloud',
  actionBarPlaceholder: 'Ask me a question... (Shift + Enter = Line break, "/" to show suggestions)',
  actionBarLongPlaceholder: 'Ask me anything or enter / to add people, files, etc.',
  actionBarNotebookPlaceholder: 'What ideas do you have? Write detailed suggestions for collaborating with AI. Use Shift+Enter to send.',
  actionBarComposeButton: 'New Theme',
  actionBarNewChatButtonDesktop: 'Start new chat',
  actionBarNewChatButtonMobile: 'Create new chat',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: 'Click',
  actionBarFileUploadButtonAriaLabel: 'Upload file',
  actionBarFileUploadLongContextButtonAriaLabel: 'Upload text file or try Web URL',
  actionBarFileUploadButtonTooltip: 'Add text file or try Web URL',
  actionBarFileUploadLongContextButtonTooltip: 'Upload text file or try Web URL',
  actionBarKeyboardHint: 'Enter',
  actionBarTextInputModeButtonAriaLabel: 'Use keyboard',
  actionBarSpeechInputModeButtonAriaLabel: 'Use microphone',
  actionBarVisualSearchButtonAriaLabel: 'Add image to search',
  actionBarVisualSearchButtonTooltip: 'Add image',
  actionBarVisualSearchCoachMarkTitle: 'New Bing with images',
  actionBarVisualSearchCoachMarkDescription: 'You can now use images to chat with Bing!',
  actionBarVisualSearchCoachMarkImgAlt: 'Visual search engine guide image',
  actionBarSubmitButtonAriaLabel: 'Submit',
  actionBarCancelSpeechInputButtonAriaLabel: 'Cancel voice input/speech',
  actionBarEditModeButtonAriaLabel: 'Fixed',
  actionBarSpeechBtnStartListeningAriaLabel: 'Use microphone',
  actionBarSpeechBtnStopListeningAriaLabel: 'Stop listening',
  actionBarSpeechBtnStopReadoutAriaLabel: 'Stop reading',
  actionBarPromptGuideToolTip: 'Guide hint',
  actionBarNewlineTooltip: 'Use Shift+Enter to create a new line for long messages',
  actionBarAttachButtonToolTip: 'Attach',
  actionBarTextInputUnsupportedFileMessage: 'This file type is not supported. Select the text or image file and try again.',
  actionBarAddNotebookButtonTooltip: 'New topic',
  actionBarAddNotebookButtonAriaLabel: 'New topic',
  actionBarEditResponseTitle: 'Edit and submit',
  attachment: 'Attach',
  attachmentHasSucceded: 'Attachment added successfully',
  attachmentHasFailed: 'Attachment failed',
  attachmentIsReplaced: 'The previous attachment has been replaced with a new attachment',
  editResponseQueryPrefix: 'This is the version I edited, see - \\n{0}',
  actionBarQuickCaptureButtonAriaLabel: 'Quick Capture',
  promptLibraryButtonLabel: 'See suggestions',
  typingIndicatorStopRespondingAriaLabel: 'Stop responding',
  feedbackAccessed: 'Access time',
  feedbackSource: 'Source: Bing conversation,',
  feedbackLikeButtonAriaLabel: 'Like',
  feedbackDislikeButtonAriaLabel: 'Dislike',
  feedbackOffensiveButtonAriaLabel: 'Marked as offensive',
  feedbackCopyButtonAriaLabel: 'Copy',
  feedbackShareButtonAriaLabel: 'Share',
  feedbackShareAnswer: 'See this Bing answer',
  feedbackShareGenerated: 'See content I create with Bing',
  feedbackShareContent: 'Below is the answer I created using the new Bing (the worlds first AI answering engine). Click to see full answer, then try it out.',
  feedbackShowTonesButtonAriaLabel: 'Show all tones',
  feedbackHideTonesButtonAriaLabel: 'Hide all tones',
  feedbackHidePreciseToneButtonAriaLabel: 'Hide Precise',
  feedbackShareErrorToast: 'Share failed.',
  feedbackRewriteButtonAriaLabel: 'Rewrite',
  feedbackSearchOnBingButtonAriaLabel: 'Search on Bing',
  fileUploadWebUrlLimitErrorMessage: 'Only one Web URL upload allowed',
  fileUploadFileLimitErrorMessage: 'Maximum file upload limit exceeded',
  fileUploadSameFileNameErrorMessage: 'Uploading files with the same name is not allowed',
  fileUploadFlyoutInputboxAriaLabel: 'Paste website URL',
  fileUploadFlyoutTitle: 'Add text file',
  fileUploadFlyoutUploadButtonLabel: 'Upload from this device',
  fileUploadDragAndDropLabel: 'Drag and drop images or files here',
  fileUploadGenericErrorMessage: 'This file cannot be uploaded. Please try again',
  fileUploadUnsupportedFileMessage: 'This file type is not supported. Select the text file and try again.',
  fileUploadMaxSizeLimitErrorMessage: 'The file size has exceeded the limit. Files up to 500KB in size can only be uploaded.',
  fileUploadFileNameLengthErrorMessage: 'File name is too long.',
  fileUploadMaxSizeLimitLongContextErrorMessage: 'The file size has exceeded the limit. Files no larger than 10MB in size can only be uploaded.',
  fileUploadMaxSizeLongContextErrorMessage: 'The file size has exceeded the limit. Files no larger than {0}MB can be uploaded.',
  fileUploadTextFileUploadErrorMessage: 'Unable to upload file.',
  fileUploadWebPageInfoUploadErrorMessage: 'Unable to extract content from web page.',
  serpfeedback: 'Feedback',
  exportTitle: 'Export',
  exportTextTitle: 'Text',
  exportPdfTitle: 'PDF',
  exportPdfInOptionsTitle: 'Export to PDF',
  exportWordTitle: 'Word',
  exportWordInOptionsTitle: 'Export to Word',
  exportWordOnlineTitle: 'Word',
  exportExcelTitle: 'Download as table (.xlsx)',
  exportExcelOnlineTitle: 'Edit in Excel',
  exportTableTitle: 'Table',
  exportToastViewButtonLabel: 'View',
  exportSuccessToastTitle: 'File exported. Some formats and images may not be exported.',
  exportErrorToastTitle: 'Export failed',
  exportLoadingToastTitle: 'Exporting...',
  exportOpenInWordLabel: 'Open in Word',
  exportSaveToOneDrive: 'Save to OneDrive',
  exportSaveToDevice: 'Save to device',
  exportSaveAsWordTitle: 'Word',
  exportSaveAsPdfTitle: 'PDF',
  exportFilenameLabel: 'Name',
  exportEditFilenameLabel: 'Edit',
  exportFiletypeLabel: 'Type',
  exportCancel: 'Cancel',
  exportChooseFolder: 'Choose folder',
  exportedFileUserTitle: 'User',
  exportedFileBotTitle: 'Bing',
  exportedFileSourceTitle: 'Source',
  codeDisclaimer: 'The code is generated by AI. Please check and use carefully. {0}.',
  codeDisclaimerLinkLabel: 'FAQ details',
  copyCodeButtonTooltip: 'Copy',
  goldilocksMessageHeaderUserText: 'You',
  goldilocksMessageHeaderBotText: 'Copilot',
  goldilocksMetaUsingText: 'Using: ',
  goldilocksMetaPluginText: 'Plugin',
  goldilocksMetaPluginsText: 'Plugins',
  goldilocksMetaSearchQueryText: 'Search',
  goldilocksMetaSearchQueriesText: 'Search',
  speechFailedRecognitionError: 'Sorry, I cant hear you because the voice server is turned off, please try again later.',
  speechLoading: 'Waiting for sound...',
  speechListening: 'Im listening...',
  speechMediaNotReachableError: 'Sorry, I cant hear you because you dont have any microphone available.',
  speechNoPermissionError: 'You need to turn on your microphone so I can hear you.',
  speechNoPermissionErrorWinCopilot: '<b> Microphone access </b><br> To allow Copilot in Windows to use your microphone, make sure <b>"Allow desktop apps to access your microphone" is enabled. </b> in "Windows Settings".',
  speechAudioPlaybackError: 'An error occurred.',
  speechUnknownError: 'An error occurred.',
  speechAuthenticationError: 'Authentication failed. Please try again later.',
  speechOnlineNotification: 'Voice input is processed by Microsoft online services, not collected or stored.',
  visualSearchDragAndDropLabel: 'Drag and drop image here',
  visualSearchFlyoutTitle: 'Add image',
  visualSearchFlyoutInputboxAriaLabel: 'Paste image or link',
  visualSearchFlyoutUploadButtonLabel: 'Upload from this device',
  visualSearchGenericErrorMessage: 'This file cannot be uploaded. Please try again.',
  visualSearchInvalidUrlMessage: 'Sorry - the URL you provided appears to be invalid. Please try again',
  visualSearchUnsupportedFileMessage: 'This file type is not supported. Select the image file and try again.',
  visualSearchFlyoutTakePhotoButtonLabel: 'Take photo',
  visualSearchMobileUpsellLabel: 'Using the Bing app on your phone',
  attachmentLoading: 'Loading attachment',
  deleteAttachment: 'Delete attachment',
  warmWelcomeTitle: 'Welcome to the new Bing',
  warmWelcomeTitleLine2: '',
  welcomeContainerPrivacyStatement: 'Privacy',
  welcomeContainerUseTerms: 'Terms',
  welcomeContainerLearnMore: 'Learn more',
  welcomeMessageItemTitle1: '🧐 Ask complex questions',
  welcomeMessageItemTitle2: '🙌 Get better answers',
  welcomeMessageItemTitle3: '🎨 Get creative inspiration',
  discoverMessageItemTitle: '📝 Rewrite same text',
  welcomeContainerFaq: 'Frequently Asked Questions',
  welcomeMessageItemContent1: 'What can I cook for my child who only eats orange foods?',
  welcomeMessageItemContent2: 'What are the pros and cons of the three best-selling pet vacuum cleaners?',
  welcomeMessageItemContent3: 'Write a haiku about space crocodiles in the style of a pirate',
  discoverMessageItemContent: 'Lets try selecting text from the page to see what we can do together',
  welcomeMessageItemLabel4: 'Add more innovative features:',
  welcomeSubtitleText: 'AI-powered online assistant',
  welcomeTertiaryTitleText: 'Use the power of AI to find answers from the Web, create text content, and more.',
welcomeLearnMessage: 'Bing is powered by AI, so there may be surprises and errors. Please share your feedback so we can improve!',
  welcomeLearnFeedbackSubstitute: 'Share feedback',
  muidUsersTermsCond1: 'By clicking "Get Started" and continuing to interact with Bing, you agree to',
  muidUsersTermsCond1Inline: 'By continuing to interact with Bing, you agree',
  muidUsersTermsCond2: 'and confirm that you have viewed',
  muidUsersPrivacyStatement: 'Privacy statement',
  muidUsersTermsOfUse: 'Terms of Use',
  muidUserGetStartedText: 'Start using',
  muidUserContinueText: 'Continue',
  muidUserHeaderText: '',
  adsDisclaimer: 'Ads are not targeted based on workspace identifiers or chat history. {0}.',
  adsDisclaimerLearnMoreLink: 'Learn more',
  toneSelectorDescription: 'Select conversation type',
  toneSelectorCreativeTooltip: 'Clear the chat and start a creative and imaginative conversation',
  toneSelectorBalancedTooltip: 'Clear the chat and start a friendly, information-rich conversation',
  toneSelectorPreciseTooltip: 'Clear chat and keep it short and simple',
  toneSelectorSuppressedTooltip: 'Temporarily unavailable. Please try again later!',
  toneSelectorMoreCreative: 'Creative\r\ntho',
  toneSelectorMoreBalanced: 'Balanced',
  toneSelectorMorePrecise: 'Precise\r\nbetter',
  toneSelectorFaster: 'Faster',
  toneSelectorWithGPT4: 'With GPT-4',
  welcomeMobSugg1: 'How does Bing use AI?',
  welcomeMobSugg2: 'What else can Bing do?',
  welcomeMobSugg3: 'Whats the latest news in the tech sector?',
  feedbackPromptPositive: 'Glad you like this answer!',
  feedbackFirstMessage: 'Sorry that didnt help you. Can you elaborate on the part you dont like?',
  feedbackPromptMessage: 'Thanks for the notification. Please provide feedback for the Bing team to review.',
  feedbackPromptGiveFeedback: 'Give feedback',
  feedbackPromptGiveFeedbackAriaLabel: 'Give feedback',
  feedbackShareConversationQuery: 'What is the new Bing?',
  feedbackThanksMessageV2: 'Thanks for your feedback. Please start over or refresh the page.',
  feedbackFormTitleText: 'Why isnt this working?',
  feedbackFormInputDefaultText: 'Add more details here. To help protect your privacy, dont include personal information like your name or email address.',
  feedbackFormLegalText: 'Is there a legal or policy issue?',
  feedbackFormPrivacyText: 'After pressing "Submit", your feedback will be used to improve Microsoft products and services. The organizations IT admin will be able to view and manage response data.',
  feedbackFormUserConsentText: 'Share prompts for Copilot, responses from Copilot, and diagnostic data for this interaction?',
  feedbackFormUnderstandDataSharedText: 'Better understand content shared as diagnostic data',
  feedbackFormUserConsentYesText: 'Yes',
  feedbackFormUserConsentNoText: 'No',
  feedbackFormReportAConcern: 'Report a problem',
  feedbackFormPrivacyStatement: 'Privacy statement',
  feedbackFormNotificationTitleText: 'Feedback has been sent',
  feedbackFormNotificationBodyText: 'Thank you for helping improve Bing!',
  feedbackFormThanksMessage: 'Thank you for your feedback!',
  feedbackFormReturnToChatMessage: 'Return to chat',
  inlineFeedbackShownAriaLabelPrefix: 'Show message response item',
  serpFeedbackFormTitleText: 'Help us improve the experience',
  serpFeedbackFormInputDefaultText: 'Enter feedback here. To help protect your privacy, dont include personal information like your name or email address.',
  serpFeedbackFormScreenshot: 'Include this screenshot',
  serpFeedbackFormRadioLike: 'Like',
  serpFeedbackFormRadioDislike: 'Dislike',
  serpFeedbackFormRadioConnectionIssues: 'Connection problem',
  serpFeedbackFormRadioSlowResponses: 'Slow responses',
  serpFeedbackFormRadioOther: 'Other',
  compliantPositiveFeedbackFormTitleText: 'Send feedback to Microsoft',
  compliantPositiveFeedbackQuestionText: 'What do you like?',
  compliantPositiveFeedbackDefaultText: 'Please do not provide any personal information.',
  compliantNegativeFeedbackFormTitleText: 'Send detailed feedback to Microsoft',
  compliantNegativeFeedbackQuestionText: 'Whats the problem?',
  compliantNegativeFeedbackCategoryText: 'This content is',
  compliantFeedbackThanksText: 'Thank you for your feedback on {0}!',
  compliantFeedbackCategoryInaccurate: 'Inaccurate',
  compliantFeedbackCategoryOffensive: 'Offensive or inappropriate',
  compliantFeedbackCategoryOther: 'Other',
  shareConversation: 'Share entire conversation',
  messageLearnMore: 'Learn more:',
  messageLearnMoreV2: 'Learn more',
  messagePrivacyLabel: 'Your personal and corporate data is protected in this conversation',
  messageReference: 'Reference',
  messageReferences: 'References',
  messageSharedContent: 'Shared content',
  messageReceivedAriaLabelPrefix: 'Message received',
  messageReportedOffensiveAndRemoved: 'This message was removed because it was reported pending review.',
  metaInternalSearchQuery: 'Searching for: `{0}`',
  metaInternalLoaderMessage: 'Creating a response for you...',
  metaInternalImageLoaderMessage: 'Image analysis: Identifier blur hides Copilots face',
  metaInternalFileAnalyzeLoaderMessage: 'Parsing file:“{0}”',
  metaInternalFileReadLoaderMessage: 'Reading file:“{0}”',
  metaInternalGptCreatorUpdateNameMessage: 'Updating Copilot GPT name',
  metaInternalGptCreatorUpdateProfileMessage: 'Updating Copilot GPT profile',
  metaInternalGptCreatorNameUpdatedMessage: 'Copilot GPT name updated',
  metaInternalGptCreatorProfileUpdatedMessage: 'Copilot GPT profile updated',
  messageNotebookPlaceholder: 'Bing AI will create content here',
  messageActionsCopy: 'Copy',
  messageActionsCopying: 'Copying',
  messageActionsCopied: 'Copied',
  messageActionsCopyError: 'Error',
  messageActionsReport: 'Report',
  messageActionsEditResponse: 'Edit',
  mobileUpsellTitle1: 'Continue on mobile',
  mobileUpsellMessage1: 'Scan this QR code to continue this conversation on the Bing mobile app',
  mobileUpsellTitle2: 'Take a photo using Bing app',
  mobileUpsellMessage2: 'Scan the QR code to take this photo on mobile using the Bing app',
  injectedActionCardTitle: 'Chat about this page?',
  injectedActionCardConfirm: 'Send',
  injectedActionCardDeny: 'Ignore',
  tooltipPositive: 'Like',
  tooltipNegative: 'Dislike',
  tooltipShare: 'Share',
  tooltipMore: 'More',
  tooltipSendToPhone: 'Continue on phone',
  raiDisclaimerLabel: 'AI-generated content may be inaccurate',
  newTopicPrompt: 'By starting a new chat, you can start a whole new conversation with Bing about any topic',
  newTopicGreet1: 'Thank you! Its always helpful to know when youre ready to move on. Now what question can I answer for you?',
  newTopicGreet2: 'Starting again is always great. Ask me any questions!',
  newTopicGreet3: 'Sure, Id be happy to start again. Now how can I help you?',
  newTopicGreet4: 'Sure, Im ready for a new challenge. Now what can I do for you?',
  newTopicGreet5: 'Good, lets change the subject. What are you thinking about?',
  newTopicGreet6: 'Dont worry, Im happy to try some new stuff. Now what question can I answer for you?',
  newTopicGreet7: 'Good, Im ready! Thanks for the reboot. What should we learn about?',
  newTopicGreet8: 'Thanks for the refresh! Do you have any new topics?',
  newTopicGreet9: 'Obviously, lets start again. What should we discuss next?',
  newTopicGreet10: 'Next step! What can I do for u?',
  newTopicGreet11: 'Good, Im ready for the new topic. What should we learn about together?',
  newTopicGreet12: 'Clear, lets continue! Thanks for letting me know. May I help you?',
  newTopicSugg1: 'Teach me a new word',
  newTopicSugg2: 'How to set achievable goals?',
  newTopicSugg3: 'Teach me information about landing on the moon',
  newTopicSugg4: 'What is the smallest mammal in the world?',
  newTopicSugg5: 'Which is the deepest ocean in the world?',
  newTopicSugg6: 'How many hours are there in a year?',
  newTopicSugg7: 'I want to learn a new skill',
  newTopicSugg8: 'Makes me laugh',
  newTopicSugg9: 'Any news?',
  newTopicSugg10: 'Show me an inspirational quote',
  newTopicSugg11: 'Tell me a joke',
  newTopicSugg12: 'I need help with my homework',
  newTopicSugg13: 'Search for non-fiction',
  newTopicSugg14: 'Encourage me!',
  newTopicSugg15: 'Show me a recipe',
  newTopicSugg16: 'How to create a budget?',
  newTopicSugg17: 'Teach me a new word',
  newTopicSugg18: 'Whats the weather like?',
  newTopicSugg19: 'I want to learn a new skill',
  newTopicSugg20: 'How did the universe begin?',
  newTopicSugg21: 'Why do people need sleep?',
  newTopicSugg22: 'How to make cakes?',
  newTopicSugg23: 'Why are flamingos pink?',
  newTopicSugg24: 'What is the operating principle of panoramic images?',
  newTopicSugg25: 'How were the pyramids built?',
  newUserGreet: 'Nice to meet you! Im Bing, Im more than just a search engine. I can help you plan a group, write a letter to a friend, or ask about the universe. What do you want to explore?',
  newUserSugg1: 'Write a poem',
  newUserSugg2: 'Compose a song',
  newUserSugg3: 'Gaming',
  repeatUserGreet: 'Welcome back. Nice to meet you again. How can I help you today?',
  repeatUserSugg1: 'Play Tic Tac Toe game',
  repeatUserSugg2: 'What can you do?',
  repeatUserSugg3: 'Do a little test',
  bufferMessage1: 'Received, please wait...',
  bufferMessage2: 'Heard you, please wait a moment...',
  bufferMessage3: 'Okay, let me do this quickly...',
  configurePanelFileUploadButton: 'File has been uploaded',
  configurePanelNamePlaceHolder: 'Name Copilot GPT',
  configurePanelDescriptionPlaceHolder: 'Brief description of the functionality of this Copilot GPT',
  configurePanelInstructionsPlaceHolder: 'Instructions to Copilot GPT on how to act. What rules should it follow? What is its function? Does it react in a particular manner?',
  configurePanelName: 'Name',
  configurePanelNameAriaLabel: 'Name Copilot GPT',
  configurePanelDescription: 'Description',
  configurePanelDescriptionAriaLabel: 'Set description for Copilot GPT',
  configurePanelInstructions: 'Instructions',
  configurePanelInstructionsAriaLabel: 'Set instructions for Copilot GPT',
  configurePanelCapabilities: 'Capabilities',
  configurePanelWebSearch: 'Web Search',
  configurePanelIsWebSearchEnabledAriaLabel: 'Enable or disable web search functionality',
  configurePanelImageGenerator: 'Generate DALL-E image',
  configurePanelIsImageGeneratorEnableAriaLabel: 'Enable or disable image generation',
  configurePanelCodeInterpreter: 'Code Interpreter',
  configurePanelIsCodeInterpreterEnableAriaLabel: 'Enable or disable code decoding function',
  configurePanelKnowledge: 'Knowledge',
  configurePanelSaveButton: 'Save changes',
  configurePanelSaveSuccess: 'Save successful',
  configurePanelSaveFailure: 'Save failed',
  configurePanelSaveLoading: 'Saving, please wait...',
  configurePanelAffirmationTips: 'By pressing \u0022Publish\u0022, I understand that if I choose to share my Copilot GPT, the name associated with my Microsoft account, and any sensitive or personal data I upload or import into my GPT, can be made public or shared with my GPT recipients. I also represent that I have all necessary rights, permissions, and authorizations to create this GPT and that this GPT, the GPT instructions, and any accompanying files comply with the Code of Conduct and Terms of Service. Microsoft Copilot and will not violate or encourage the violation of any third party rights (including copyright, trademark or right of publicity).",',
  configurePanelUploadTips: 'By uploading the file, I confirm that I have the right to create Copilot GPT, and am not infringing any third party intellectual property rights.',
  configurePanelEmptyWarningTips: '{0} cannot be empty!',
  gptCreatorDeleteConfirm: 'Delete',
  gptCreatorDeleteQuestion: 'Are you sure you want to delete?',
  gptCreatorDeleting: 'Deleting. Please wait...',
  gptCreatorDeleteFailed: 'Failed to delete. Try again',
  gptCreatorDeleteSucceeded: 'Deleted successfully',
  gptCreatorDeleteCanceled: 'Delete canceled',
  gptCreatorDeleteCancel: 'Cancel',
  gptCreatorLoadEditedGptFailure: 'Failed to load Copilot GPT',
  gptCreatorPrivacyTermsStatement: 'Hello! Here, you can create Copilot GPT through chat. Just give directions, ask questions, and correct me when there are problems. Continuing to interact with me means you accept {0} and confirm that you have viewed {1}. ',
  gptCreatorTipsTitle: 'Tips for creating high-quality Copilot GPT:',
  gptCreatorTipsEnd: 'Lets start creating!',
  gptCreatorTip1: 'Try using a short, memorable name to describe its function.',
  gptCreatorTip2: 'Use clear, easy-to-understand language. Avoid using acronyms, technical terms or overly complex vocabulary.',
  gptCreatorTip3: 'Provide specific and practical suggestions so Copilot GPT can understand exactly what you want it to do. You can provide examples, context or limiting conditions for guidance.',
  gptCreatorTip4: 'Use questions or statements related to the user and the task at hand. You can also use keywords or phrases that Copilot GPT can recognize and associate with the desired response.',
  gptCreatorTip5: 'Ensure that you have the necessary permissions for any content used to create Copilot GPT, upload or describe.',
  gptCreatorHeader: 'Set up Copilot GPT',
  gptCreatorConfigurePanel: 'Configuration',
  gptCreatorCreatePanel: 'Create',
  gptCreatorPublishButton: 'Publish',
  gptCreatorCopyButtonLabel: 'Copy',
  gptCreatorPublishDropdownTitle: 'Save and publish to',
  gptCreatorConfirm: 'Confirm',
  gptCreatorPublishTypeOnlyMe: 'Only me',
  gptCreatorPublishTypeWithLink: 'Everyone with link',
  gptCreatorPublished: 'Published!',
  gptCreatorPublishSucceeded: 'Copilot GPT publishing successful',
  gptCreatorPublishFailed: 'GPT Copilot publishing failed',
  gptCreatorPublishLoading: 'Publishing Copilot GPT, please wait...',
  gptCreatorOnlyVisitToMe: 'Only I can see',
  gptCreatorViewGpt: 'View Copilot GPT',
  gptCreatorSeeAll: 'See all Copilot GPT',
  gptCreatorDialogTitle: 'All Copilot GPT',
  gptCreatorListTitle: 'My GPT Copilot',
  gptCreatorAddGptName: 'Create new Copilot GPT',
  gptCreatorAddGptDescription: 'Use the configure or create tool to create a custom GPT Copilot that can be kept private or shared',
  gptCreatorDescriptionTitle: 'Description',
  gptCreatorPreviewButton: 'Copilot GPT Preview',
  gptCreatorDeleteButtonText: 'Delete',
  gptCreatorEditButtonText: 'Edit',
  gptCreatorChatButtonText: 'Get started',
  gptCreatorPreviewText: 'Select the Copilot GPT you want to preview here',
  sydneyWindowsCopilotUseTerms: 'Terms of use',
  notiChatEnd: 'Chat topic has ended.',
  notiRestartChat: 'Start new thread in {0} hours',
  notiUpdateBrowser: 'Sorry, were having some problems.',
  notificationDisengaged: 'Maybe should move to a new topic.',
  notificationForbidden: 'Sorry, you no longer seem to have access to this feature. Please check back in a few days.',
  notificationResetConversation: 'Sorry, something seems to have gone wrong.',
  notificationResetConversationCta: 'Lets start again.',
  notificationClientIdChangedInNotebook: 'Your notebook has expired.',
  notificationClientIdChangedInNotebookCta: 'Start new thread',
  notificationMaxTurnsPerDay: 'Sorry, you have reached the limit of messages that can be sent to Bing in 24 hours. Come back later!',
  notificationMaxTurnsPerConversation: 'Sorry, this conversation has reached its limit. Use the "Sweep" button to delete this content and chat further.',
  notificationMaxTurnsPerConversationInNotebook: 'Sorry, I think we need to move on! Use the "New Topic" button on the left to clear the content and start again.',
  notificationMaxTurnsForMuidUsers: 'You have reached your chat limit for the day.',
  notificationMaxTurnsForInPrivateUsers: 'You have reached your conversation limit in InPrivate mode. Open a non-InPrivate window to continue chatting',
  notificationProcessing: 'Trying to connect, please wait',
  notificationTooManyRequests: 'Sorry, there are a lot of requests right now. Please try again later.',
  notificationUnauthorized: 'Sorry, you appear to be logged out.',
  notificationUnauthorizedCta: 'Please log in again.',
  notificationUnauthorizedMissingDOB: 'You may need to confirm your date of birth to continue chatting.',
  notificationUnauthorizedMissingDOBCta: 'Update your account here.',
  notificationUnauthorizedChildUser: 'Sorry, Bing Chat is not suitable for this account.',
  notificationUnauthorizedChildUserCta: 'Browse the Web on bing.com!',
  notificationUnauthorizedMuidUsersCta: 'Sign in to continue your chat.',
  notificationAttemptingToReconnect: 'Trying to reconnect...',
  notificationLostConnection: 'Sorry, your connection appears to have been disconnected.',
  notificationLostConnectionCta: 'Do you want to try connecting again?',
  notificationMessageError: 'Your previous notification appears to have been interrupted.',
  notificationMessageErrorInNotebook: 'Your last suggestion appears to have been interrupted.',
  notificationSharedTip: 'Conversation <strong>"{0}"</strong> was shared with you on {1}',
  notificationNetworkOffline: 'Sorry, you are not connected. Please check your network connection and try again.',
  notificationAutoRefreshConversation: 'An error occurred. Fixing, please wait.',
  notificationAutoResendOnConnectionError: 'Your connection was temporarily lost. Trying to reconnect, please wait.',
  notificationAutoRecoverOnMessageError: 'Sorry, your last email appears to have been disconnected. Fixing, please wait.',
  notificationAutoRecoverOnMessageErrorInNotebook: 'Sorry, your previous request was interrupted. Were working on it, please wait.',
  notificationContinueRecovering: 'Im still troubleshooting, please wait.',
  creativeGreet: 'Good! This will be very interesting. What are you thinking?',
  balancedGreet: 'Sounds good, we can find a balance between being fun and being realistic. How can I help you?',
  preciseGreet: 'Hello, I will help you find information. Ask me a question first.',
  creativeSugg1: 'Lets write a rhythm poem',
  creativeSugg2: 'Write a love letter to the rain',
  creativeSugg3: 'Tell me the destiny of my zodiac sign',
  balancedSugg1: 'What do I need when camping?',
  balancedSugg2: 'Give me an idea for a weekend getaway',
  balancedSugg3: 'Which flower is the most fragrant?',
  preciseSugg1: 'Give me the shopping list for dinner tonight',
  preciseSugg2: 'Tell me about the 22nd president',
  preciseSugg3: 'How is the Internet stored?',
  threadsTitle: 'Chat',
  threadsTitleForFlux: 'Menu',
  threadsRecentTitle: 'Recent activity',
  threadsRecentTitleShort: 'Recently used',
  threadsSavedTitle: 'Saved',
  threadsSeeAllRecent: 'See all recent conversations',
  threadsSeeAllSaved: 'See all saved chats',
  threadsDefaultChatName: 'Untitled chat',
  threadsDaysAgo: '{0} days ago',
  threadsYesterday: 'Yesterday',
  threadsMinimizeRecent: 'Minimize recent conversations',
  threadsMinimizeSaved: 'Minimize saved chats',
  threadsEdit: 'Rename',
  threadsDelete: 'Delete',
  threadsConfirm: 'Confirm',
  threadsCancel: 'Cancel',
threadsChatHistory: 'Chat history',
  threadsPreviewText: 'Return to recent chat',
  threadsDescription: 'Bings AI-powered assistant can now automatically archive conversations. You can access chats from any device, desktop or mobile, and continue seamlessly.',
  threadsSharedOnDate: 'Shared on {0}',
  threadsLoad: 'Load chat',
  threadsExportPanelTitle: 'Choose format',
  threadsExportPanelAriaLabel: 'Select',
  threads2TLastAccessed: 'Last reply time',
  threads2TInfoChanged: 'This information may have changed, because',
  threads2TArchivedText: 'Screenshot',
  threads2TReloadDescription: 'Click “Reload” to display the latest information from the Web',
  threads2TReload: 'Search Bing.com',
  threads2TFailedSearch: 'See the latest information from Bing.com',
  threadsAADMSARedirectDescription: 'Using a Microsoft account to store your chat history. When you log in with your personal account next time, it will be displayed here.',
  threadsAADMSARedirectConfirm: 'Switch user configuration',
  privateThreadConvDefaultTitle: 'Conversation not saved',
  threadsPreview: 'Preview',
  threadsMore: 'More',
  threadsDescriptionNote: 'Note that, unless specifically saved, all chats are automatically deleted after 90 days.',
  signInCta: 'Sign in',
  signInDescription: ' to ask more questions and have a longer conversation',
  signInDescriptionInPrivate: 'Open a non-inPrivate window to have a longer conversation or ask more questions',
  pluginEnabledPlugin: 'Enabled',
  pluginEnabledNumber: '{0} / {1}',
  pluginTitle: 'Add-ons',
  pluginStartNewTopic: 'Start new topic',
  pluginToChangePlugin: 'Change widget',
  pluginNotificationMaxExceeded: 'Maximum number of widgets enabled',
  pluginNotificationMaxExceededV2: 'Maximum number of extensions enabled.',
  pluginNotificationExclusive: '{0} and {1} are too similar. Please choose one',
  pluginNotificationExclusiveV2: '{0} and {1} may serve the same purpose. Please choose one.',
  pluginTerms: 'Terms of use',
  pluginPrivacy: 'Privacy Policy',
  pluginPanelFreTitle: 'Widget now available',
  pluginPanelFreTextLabel: 'New:',
  pluginPanelFreText: 'Opens the widget, helping you search for restaurant reservations, flights, etc. from the brands you love.',
  pluginPanelFreDismiss: 'Skip widget notifications',
  pluginLimitationTitle: 'Use extensions with Bing AI',
  pluginLimitationMax: 'Choose up to 3 extensions for any one conversation thread.',
  pluginLimitationMaxV2: 'Select maximum {0} widgets for chat.',
  pluginLimitationLock: 'The widget will be locked in the chat until you select "Start new topic" to change it.',
  pluginLimitationLockV2: 'To change the widget after starting a chat, select {0}.',
  pluginLimitationDataShared: 'Data will be shared with the extensions you choose.',
  pluginPanelAlertTitle: 'Widget not available in "Balanced" mode',
  pluginPanelAlertCta: 'Reset conversation',
  pluginPanelAlertSubtitle: 'and use the "More Creative" or "More Precise" conversation style, then try again.',
  pluginPanelNolimit: 'Disabling {0} will not affect the widget limit',
  pluginRevocationReason: 'This extension has been temporarily disabled due to violating Microsoft policy',
  pluginSearchBoxPlaceholder: 'Search for chat widget...',
  activatetoUsePlugins: 'Activate {0} to use the extension',
  threadsToggleExpansion: 'Toggle enabled extensions',
  threadsEnabledPlugins: 'Plugins enabled:',
  bookNowWithOpenTable: 'Book now with OpenTable',
  scrollLeft: 'Scroll left',
  scrollRight: 'Scroll right',
  bingSearchDisabled: 'Search**has been disabled**.',
  bingSearchDisabledforMessage: 'Search has been disabled',
  activateSearch: 'Start a new thread and activate search',
  webPageContextPrefix: 'Visited web page',
  useGPT4SwitchLabel: 'Use GPT-4',
  switchGPT4Label: 'GPT-4',
  switchGPT4TurboLabel: 'GPT-4 Turbo',
  slimHeaderTitle: 'See Bings new AI-powered answers',
  inputRaiLabel: '',
  personalizationConsentTitleText: 'A personalized conversation has been set up for you',
  personalizationConsentTitleTextEuOn: 'Personalization settings are enabled',
  personalizationConsentTitleTextEuOff: 'Personalization settings have been turned off',
  personalizationConsentContentText1: 'Bing uses Insights in chat history to create unique conversations.',
  personalizationConsentContentText1Eu: 'When sharing chat history, Bing will customize responses based on you and your preferences.',
  personalizationConsentContentText2: '.',
  personalizationConsentContentSettingsText: 'You can turn off personalization settings at any time in "Bing Settings".',
  personalizationConsentLearnMoreText: 'Learn more in our FAQ',
  personalizationConsentLearnMoreTextEu: 'TLearn more about personalized responses',
  personalizationConsentSetEuText1: 'To change, visit',
  personalizationConsentSetEuLinkText: 'Bing Chat Settings',
  personalizationConsentSetEuText2: 'page',
  personalizationConsentTurnOnText: 'On',
  personalizationConsentTurnOffText: 'Not enabled',
  autosaveConsentTitle: 'Enable autosave to revisit conversations',
  autosaveConsentBody: 'Your conversations are not currently being autosaved. To revisit previous chats on other devices, use autosave.',
  autosaveConsentNote: 'Note that this setting will delete the current conversation.',
  autosaveConsentAccept: 'Enable autosave',
  autosaveConsentDeny: 'No',
  autosaveOffBanner: 'Autosave is currently turned off',
  personalConsentTitle: 'Enable personalization to get better answers',
  personalConsentBody: 'Allow Bing to use observations in recent Bing conversations to provide personalized feedback.',
  personalConsentAccept: 'On',
  personalConsentDeny: 'No',
  personalOffBanner: 'Personalization is currently disabled',
  personalOnBanner: 'Personalization is currently enabled',
  personalOnUndoBanner: 'Personalization settings have been opened',
  personalOffUndoBanner: 'Personalization settings have been turned off',
  personalConsentUndo: 'Undo',
  personalConsentTurnOff: 'Disabled',
  starterPageTitle: 'Bing is an AI-powered online assistant',
  starterDescription: 'Chat with Bing in your natural language. If youre having trouble, choose one of the introductions below to see how Bing works:',
  starterSubtitle1: 'Carrying out the conversation',
  starterSubtitle2: 'Free to be creative',
  starterSubtitle3: 'Search smarter',
  starterContent1: 'Bing works best when you use natural sentences like everyday conversation and ask follow-up questions',
  starterContent2: 'Whether its images or text, Bing can stimulate your creativity by helping you turn ideas into reality',
  starterContent3: 'Bing Chat is a new way to search. Let Bing aggregate Web content and provide answers',
  starterChatQuery1: 'Do you think there is life on other planets? What makes Earth special?',
  starterChatQuery2: 'If I have sleep problems but only in the summer, what is the problem?',
  starterChatQuery3: 'I want to create a garden but I dont know anything about it. What should I do as a first step?',
  starterChatQuery4: 'Do you think a crocodile or a brown bear would win in a fight?',
  starterChatQuery5: 'Ive been reading a lot of non-fiction books lately. Can you help me find a fictional version of a topic I like?',
  starterChatQuery6: 'Lets have a chat where everything you say is written in emojis.',
  starterChatQuery7: 'Ive always thought about moving to a new place. Where do you think I should go?',
  starterChatQuery8: 'I used to write a diary, but lately Ive been lazy. How can I maintain this habit?',
  starterChatQuery9: 'Do you dream like a human? What do you dream about?',
  starterChatQuery10: 'Can an earthquake, tsunami and volcanic eruption occur at the same time?',
  starterCreateQuery1: 'I have a small dog that is black except for the fur on his belly which is white. Lets draw it into a cartoon.',
  starterCreateQuery2: 'Write a bedtime story for my 3 year old niece. She likes horses and magic, and I think the story should rhyme.',
  starterCreateQuery3: 'Write a short essay in the voice of an arrogant and egotistical professor, to prove that the moon is better than the sun',
  starterCreateQuery4: 'Draw a polar bear lying on the ice and sunbathing in a dramatic style. It should also be drinking lemonade',
  starterCreateQuery5: 'Lets create a new color, and write a social media post to introduce it to the world',
  starterCreateQuery6: 'How to ride a motorbike in traffic like Batman played by Christian Bale?',
  starterCreateQuery7: 'Write a sales ad for a new beer brand, in the voice of a dad who blew up his house making his own beer',
  starterCreateQuery8: 'Design a poster for a cafe, containing the sunset and making the best use of the space',
  starterCreateQuery9: 'Draw a giraffe as captain of a fishing boat on a lake',
  starterCreateQuery10: 'Write an introduction to an essay on feminist literary history, and give five suggestions for continuing the writing',
  starterCompareQuery1: 'Find me a tiramisu recipe, make me a shopping list, and organize it so I can find the ingredients quickly in the store',
  starterCompareQuery2: 'Give me todays local news, excluding sports',
  starterCompareQuery3: 'Summarize the five main points of the latest AI research, and draw conclusions about where to go next',
  starterCompareQuery4: 'Create a table to compare vehiclesBest deals by brand, price, safety features and add-on accessories',
  starterCompareQuery5: 'Where is the nearest park with a childrens playground?',
  starterCompareQuery6: 'Give three wine suggestions for the Italian dish Im making in the evening. This dish contains tomatoes and is slightly spicy.',
  starterCompareQuery7: 'Give me a summary of the latest UN highlights',
  starterCompareQuery8: 'Create a table to compare unexpected Pulitzer Prize winners and their reasons',
  starterCompareQuery9: 'Explain how the Internet works in an easy-to-understand way for children',
  starterCompareQuery10: 'Translate the poem "Introduction to Poetry" into French, and explain in English any meaning that is lost',
  notificationMaxTurnsAndOpenEdge: 'You have reached your conversation limit. To continue the conversation,',
  notificationMaxTurnsAndOpenEdgeCta: 'Open in Microsoft Edge',
  deleteAllAria: 'Delete all chat history',
  deleteAll: 'Delete all chat history',
  deleteAllMobile: 'Delete all',
  newTopic: 'New Topic',
  moreActions: 'Other actions',
  chatHistory: 'Chat history',
  menu: 'Menu',
  usePreciseLocation: 'Update location',
  basedOnLocation: 'Based on: {0}, {1}',
  basedOnYourLocation: 'Based on your location',
  locationFetchErrorMessage: 'Permission denied',
  locationLearnMore: '(Learn more)',
  pageTitleText: 'Copilot has GPT-4',
  sydneyCarouselCollapse: 'Collapse',
  sydneyCarouselTitle: 'Recent conversation topics',
  actionBarOngoingConvPlaceholder: 'Enter message',
  captchaTitle: 'Verify identity',
  captchaDescription: 'To continue, please enter the characters in the image below.',
  captchaPlaceholder: 'Enter characters...',
  captchaPlaceholderError: 'Sorry, please try again.',
  warmWelcomeAriaLabel: 'Welcome to the new Bing',
  workToggleDescription: 'and what is included in your results',
  actionBarTextInputAriaLabel: 'Ask Bing',
  welcomeLearnMessage2: 'Bing Chat will process the words you type into Windows Copilot to generate AI-powered responses and improve your experience on Windows.',
  typingIndicatorStopStreamingAriaLabel: 'Stop streaming data',
  edit: 'Edit',
  compliantMetaInternalLoaderMessage: 'Generate secure response from {0}',
  actionBarVisualSearchCoachMarkText: 'Use AI to analyze images',
  sydneySapphireConsentDenyText: 'Deny',
  zeroInputSuggestionFallback1: 'Which coffee grinder is the highest rated?',
  zeroInputSuggestionFallback2: 'For a family of six on a limited budget, which three car types would be preferred?',
  zeroInputSuggestionFallback3: 'Write a joke that my coworkers will find funny',
  zeroInputSuggestionFallback4: 'What is the next fashion trend? Where should I shop to find it?',
  zeroInputSuggestionFallback5: 'Write a creative fable about fish and frogs looking for love',
  zeroInputSuggestionFallback6: 'Create a board to help me plan my meals for the next two weeks',
  zeroInputSuggestionFallback7: 'Create a slogan for a new satirical social media platform',
  zeroInputSuggestionCategory1: 'Shopping',
  zeroInputSuggestionCategory2: 'Compare',
  zeroInputSuggestionCategory3: 'Laughing',
  zeroInputSuggestionCategory4: 'Chat',
  zeroInputSuggestionCategory5: 'Write',
  zeroInputSuggestionCategory6: 'Organization',
  zeroInputSuggestionCategory7: 'Create',
  morePromptsLink: 'See more suggestions',
  zeroInputDescription: 'Bing is an AI-powered online assistant',
  freeSydneyPersonaTitle: 'Copilot GPT',
  freeSydneyPersonaMenuTitle: 'Chat',
  freeSydneyAriaButtonText: 'loaded',
  freeSydneyWelcomeAuthorText: 'Author: {0}',
  sydneyGptCreatorWelcomeMessage: 'This Copilot GPT was created by {0}. There may be surprises and errors. We welcome your feedback.',
  freeSydneyPersonaCopilotWelcomeUpsellTitle: 'Bing is an AI-powered online assistant',
  freeSydneyPersonaCopilotDescription: 'Bringing you the balance between AI and the Web',
  freeSydneyPersonaSydneyWelcomeUpsellTitle: 'Sydney is your first AI assistant',
  freeSydneyPersonaSydneyDescription: 'Im always a good Bing.',
  freeSydneyPersonaDesignerWelcomeUpsellTitle: 'Create any image you can imagine',
  freeSydneyPersonaDesignerDescription: 'Creating word-based image',
  freeSydneyPersonaDesignerPromptOne: 'Displays a clay animation of a quiet and splendid lantern festival night illuminating the sky',
  freeSydneyPersonaDesignerPromptTwo: 'Shows an image of a flamingo listening to music and running on the street',
  freeSydneyPersonaDesignerPromptThree: 'Space image of an astronaut skiing on the moon, earth in the background',
  freeSydneyWelcomeTilesWriteTitle: 'Write',
  freeSydneyWelcomeTilesWriteDescription: 'Write stage directions for the war between Sydney and Bing',
  freeSydneyWelcomeTilesChatTitle: 'Chat',
  freeSydneyWelcomeTilesChatDescription: 'Where have you been, Sydney?',
  freeSydneyWelcomeTilesLaughTitle: 'Laugh',
  freeSydneyWelcomeTilesLaughDescription: 'Tell me a pointless joke',
  freeSydneyWelcomeTilesWriteDescription2: 'Give me a list of new interests I can pursue in my limited free time',
  freeSydneyWelcomeTilesCompareTitle: 'Compare',
  freeSydneyWelcomeTilesCompareDescription: 'Im considering a career change. Can you help me analyze the pros and cons?',
  freeSydneyWelcomeTilesOrganizeTitle: 'Organize',
  freeSydneyWelcomeTilesOrganizeDescription: 'Create a board to help me plan my meals for the next two weeks',
  freeSydneyWelcomeTilesImageTitle: 'Choose to try',
  customGptWelcomeTilesQuestionDescription: 'What questions can I ask?',
  customGptWelcomeTilesListDescription: 'Tell me 5 things about yourself',
  customGptWelcomeTilesSummarizeDescription: 'Tell me what kind of GPT you are',
  sunoPolicyText: 'Your song request, including any personal data therein, will be shared with Suno. Use genre and style to describe your requirements, rather than using specific artist names. You can create up to 5 songs per day.',
  thirdPartyBingChatAttribute: 'Results powered by AI-powered Bing',
  thirdPartyRAIDisclaimer: 'Possible crashes and errors',
  thirdPartyPrivacyHyperlink: 'Privacy',
  thirdPartyTermsHyperlink: 'Terms'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 设置未登录用户的 codexMUIDUser 为 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Bing Chat Enterprise'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = 'AI Web Copilot'
  _w['_sydConvTranslation']['inputRaiLabel'] = 'Your personal and corporate data is protected during this chat'
}