/* eslint-disable */
_w['_sydBaseSpecifierPrefix'] = 'rms-answers-SharedStaticAssets-';
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'spktxtibmoff,uquopt,enelecintl,gndeleccf,gndlogcf,jbfv203,2tlocretbn,osbsdrecoff',
  sydBalOpts: 'cgptrsndlwcp,flxclmdlspwcp,gldcl1wcp,glfluxv15wcp,invocmax',
  sydCrtOpts: 'invocmax',
  sydPrcOpts: 'invocmax',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'gbacf,bggrey,1366cf,multlingcf,stibmoff,tts4,ttsvivn,caccnctacf,specedge,inosanewsmob,wrapnoins,racf,rwt2,dismmaslp,1117gndelecs0,713logprobss0,1111jbfv203,1118wcpdcl,117invocmax,10312tlocret,1025gptv_v2s0,fluxnosearch,1115fluxvs0,727nrprdrt6,727nrprdrt5,codecreator1,cacmuidarb,edgenorrwrap,tstchtadd',
  sydBaseUrl: location.origin,
  compSydRequestSource: 'cib',
  compSydRequestScenario: 'chat',
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enableSapphireSydVoiceExp: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'en-US',
  userMailId: randomString(Math.round(Math.random()*16))+'@'+randomLowercaseString(randomString(Math.round(Math.random()*12)))+'.com',
  username: randomString(Math.round(Math.random()*16)),
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableDM: true,
  enableSydImageCreate: true,
  enableToneCook: true,
toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
// 设置已登录账号的聊天对话次数
  maxTurnsPerConversation: 30,
// 设置未登录账号的聊天对话次数
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableJWTFTRFix: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForBalancedTone: true,
  enableStreamSyntheticTextResponsesForCreativeTone: true,
  enableStreamSyntheticTextResponsesForPreciseTone: true,
  syntheticStreamSpeed: 55,
  syntheticStreamSpeedForBalancedTone: 55,
  syntheticStreamSpeedForCreativeTone: 55,
  syntheticStreamSpeedForPreciseTone: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  sydSapphireUpsellVisualSearchQRCodeUrl: 'https://bingapp.microsoft.com/bing?adjust=13uz7blz_13evwnmy',
  enableSydneySapphireUpsellMessageActions: true,
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing\u0026adjust=euhmno2_oy62nz1',
  enableConvModeSwitchAjax: true,
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enablePrivacyConsent: true,
  enableFixCodeXAsBug: true,
  enableThreads: true,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableDynamicShareTitle: true,
  enableSharePreview: true,
  enableSharedHoverCitations: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableFixOnReplaceAllJSError: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  suppressPoleRSWhenEnableSydCarousel: true,
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableDelayGetChats: true,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
  enableFlux3P: true,
  disableWelcomeScreen: true,
  enableWelcomeScreenV2: true,
  codexTableVersion: true,
  enableBICHistory: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  fileUploadMaxSizeLongContext: 10000000,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableFaviconsV2: true,
  enableUserIpAddress: true,
  enableActionBarV2: true,
  speechSurface: 'desktop',
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: true,
  enableUpdateUserMessageId: true,
  enablePluginPanelFre: true,
  enableMobileFirstClickShare: true,
  personalizationInlineConsentTurn: false,
  enableNoBingSearchResponseBackground: true,
  enableNoSearchPluginMetaMessage: true,
  enableInlineAdsDynamicWidth: true,
  enableShareInThreadsHeader: true,
  enableDeleteSingleConversationMemory: true,
  enableStableAutosuggestion: true,
  threadsAutoSaveOptionset: 'autosave',
  enableUserMessageRewriteAndCopy: true,
  enableBCBSensitivityLabel: true,
  enableOneDs: true,
  enablePromptHandling: true,
  dedicatedIpType: 'unknown',
  enableCIQEmail: true,
  enableCIQAutoScoping: true,
  enableCachedContentFixForIsStartOfSession: true,
  extraNotebookOptionsSets: 'iycapbing,iyxapbing,prjupy',
  notebookMaxMessageLength: 18000,
  initialShowConvPresent: true,
  enableAttributionsV2: true,
  minimumZeroInputSuggestionCount: true,
  imageSearchFormCode: 'IACMIR',
  imageSearchEnableMediaCanvas: true,
  imageSearchMaxImageCount: 5,
  imageSearchForceSquareImages: true,
  enableRelativeSignInUrl: true,
  chatBackgroundColorOverride: 'f7f7f8',
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  autoHideConvInterval: 3600000,
  enableAjaxBundlePLoad: true,
  PLoadIID: 'SERP.5883'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: 'Please ask me if you have any questions... (Shift + Enter = new line, "/" activates suggestions)',
  actionBarAriaLabel: 'Ask Bing',
  actionBarComposeButton: 'New topic',
  actionBarNewChatButtonDesktop: 'Start a new chat',
  actionBarNewChatButtonMobile: 'chat',
  actionBarOngoingConvPlaceholder: 'Type a message',
  attachmentLoading: 'Loading attachment',
  bufferMessage1: 'I am using it, please wait',
  bufferMessage2: 'Please wait a moment',
  bufferMessage3: 'Take some time to think...',
  captchaTitle: 'Verify identity',
  captchaDescription: 'To continue, please enter the characters in the image below.',
  captchaPlaceholder: 'Enter characters...',
  captchaPlaceholderError: 'Sorry, please try again.',
  next: 'Next',
  cancel: 'Cancel',
  feedbackAccessed: 'access time',
  feedbackSource: 'Source: Dialogue with Bing,',
  feedbackShareConversationQuery: 'What is the new version of Bing?',
  messageLearnMore: 'Learn more:',
  messageReference: 'reference',
  messageReferences: 'citations',
  messagePrivacyLabel: 'Your personal and company data is protected in this chat',
  inputRaiLabel: '',
  letsChat: 'Let\'s chat',
  pause: 'Pause',
  play: 'Start game',
  speechFailedRecognitionError: 'Sorry, I can\'t hear your voice because the voice server is turned off, please try again later.',
  speechListening: 'I am listening...',
  speechLoading: 'Waiting for sound...',
  speechMediaNotReachableError: 'I am sorry, I can\'t hear your voice because you do not have a microphone available.',
  speechNoPermissionError: 'You need to enable the microphone before I can hear you.',
  speechAudioPlaybackError: 'An error occurred.',
  stop: 'Stop',
  welcomeContainerFAQs: 'Frequently asked questions',
  welcomeContainerPrivacyStatement: 'Privacy',
  welcomeContainerUseTerms: 'terms',
  welcomeContainerLearnMore: 'Learn more',
  welcomeMessageItemContent1: 'What can I do for children who are picky eaters and only eat orange food?',
  welcomeMessageItemContent2: 'What are the advantages and disadvantages of the top 3 best-selling pet vacuum cleaners?',
  welcomeMessageItemContent3: 'Write a sentence about crocodiles in space with a pirate tone',
  welcomeMessageItemTitle1: '🧐 Ask complex questions',
  welcomeMessageItemTitle2: '🙌 Get better answers',
  welcomeMessageItemTitle3: '🎨 Get creative inspiration',
  welcomeMessageItemLabel4: 'More new features in creativity:',
  warmWelcomeTitle: 'Welcome to the new Bing',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel: 'Welcome to the new Bing',
  welcomeSubtitleText: 'Online assistant SUPPORTED BY AI',
  workToggleDescription: 'and your results include what',
  feedbackFirstMessage: 'I am very sorry for not being able to help you. Can you explain the aspects you don\'t like in detail?',
  feedbackPromptMessage: 'Thank you for the reminder. Please provide feedback so that the Bing team can review it.',
  feedbackPromptGiveFeedback: 'provide feedback',
  feedbackPromptGiveFeedbackAriaLabel: 'provide feedback',
  feedbackPromptReportAConcern: 'Report a problem',
  feedbackPromptPositive: 'I\'m glad you like this answer!',
  feedbackFormTitleText: 'Why is this not working?',
  feedbackFormInputDefaultText: 'Add more details here. To help protect your privacy, please do not fill in your personal information such as your name or email address.',
  feedbackFormLegalText: 'Any legal or policy issues?',
  feedbackFormReportAConcern: 'Report a problem',
  feedbackFormNotificationTitleText: 'Feedback has been sent',
  feedbackFormNotificationBodyText: 'Thank you for helping Bing improve!',
  feedbackFormThanksMessage: 'Thank you for your feedback!',
  feedbackFormReturnToChatMessage: 'Return to chat',
  serpFeedbackFormTitleText: 'Help us improve the experience',
  serpFeedbackFormInputDefaultText: 'Enter feedback here. To help protect your privacy, please do not fill in your personal information such as your name or email address.',
  serpFeedbackFormScreenshot: 'include this screenshot',
  serpFeedbackFormRadioLike: 'Like',
  serpFeedbackFormRadioDislike: 'dislike',
  serpFeedbackFormRadioConnectionIssues: 'Connection issues',
  serpFeedbackFormRadioSlowResponses: 'Slow responses',
  serpFeedbackFormRadioOther: 'Other',
  feedbackFormUnderstandDataSharedText: 'Learn more about the content shared as diagnostic data',
  feedbackFormUserConsentText: 'Share reminders with Copilot, feedback received from Copilot and diagnostic data for this interaction?',
  feedbackFormUserConsentYesText: 'Yes',
  feedbackFormUserConsentNoText: 'No',
  feedbackFormPrivacyStatement: 'Privacy statement',
  feedbackFormPrivacyText: 'After Submitting your feedback will be used to improve Microsoft\'s products and services. The IT administrator of the organization will be able to view and manage feedback data.',
  compliantPositiveFeedbackFormTitleText: 'Send feedback to Microsoft',
  compliantPositiveFeedbackQuestionText: 'What aspects do you like?',
  compliantPositiveFeedbackDefaultText: 'Please do not provide any personal information.',
  compliantNegativeFeedbackFormTitleText: 'Send detailed feedback to Microsoft',
  compliantNegativeFeedbackCategoryText: 'This content is',
  compliantNegativeFeedbackQuestionText: 'What\'s the matter?',
  compliantFeedbackThanksText: 'Thank you for sending feedback about {0}!',
  compliantFeedbackCategoryInaccurate: 'inaccurate',
  compliantFeedbackCategoryOffensive: 'offensive or inappropriate',
  compliantFeedbackCategoryOther: 'Other',
  submit: 'Submit',
  explore: 'Browse',
  exploreMore: 'Browse more',
  metaInternalSearchQuery: 'Searching: `{0}`',
  metaInternalLoaderMessage: 'Creating an answer for you...',
  metaInternalImageLoaderMessage: 'Analyzing image: Privacy blur will hide faces in Bing chat',
  compliantMetaInternalLoaderMessage: 'Creating a privacy answer from {0}',
  messageSharedContent: 'Shared content',
  clickToView: 'Click to view',
  more: 'More',
  expand: 'Open',
  welcomeTertiaryTitleText: 'Use the power of AI to find answers from the web, create content with text, and more.',
  actionBarTextInputAriaLabel: 'Ask Bing',
  seeMore: 'See more',
  seeLess: 'See less',
  raiSuggestions: 'What is this?',
  actionBarFileUploadButtonAriaLabel: 'Search in file',
  actionBarStopStreamingAriaLabel: 'Stop streaming',
  actionBarTextInputModeButtonAriaLabel: 'Use keyboard',
  actionBarSpeechInputModeButtonAriaLabel: 'Use microphone',
  actionBarVisualSearchButtonTooltip: 'Add image',
  actionBarVisualSearchButtonAriaLabel: 'Add the image you want to search',
  actionBarVisualSearchCoachMarkTitle: 'New Bing with images',
  actionBarVisualSearchCoachMarkDescription: 'Now you can use images to chat with Bing!',
  actionBarVisualSearchCoachMarkImgAlt: 'Image suggestion visual search tool',
  actionBarSubmitButtonAriaLabel: 'Submit',
  actionBarCancelSpeechInputButtonAriaLabel: 'Cancel voice input / read out',
  actionBarEditModeButtonAriaLabel: 'Fix',
  actionBarSpeechBtnStartListeningAriaLabel: 'Use microphone',
  actionBarSpeechBtnStopListeningAriaLabel: 'Stop listening',
  actionBarSpeechBtnStopReadoutAriaLabel: 'Stop reading out',
  feedbackLikeButtonAriaLabel: 'Like',
  feedbackDislikeButtonAriaLabel: 'Dislike',
  feedbackOffensiveButtonAriaLabel: 'mark as offensive',
  feedbackCopyButtonAriaLabel: 'Copy',
  feedbackShareButtonAriaLabel: 'Share',
  messageSentAriaLabelPrefix: 'Email sent',
  messageReceivedAriaLabelPrefix: 'Message received',
  messageAttributionsCollapseBtnAriaLabel: 'Collapse',
  newTopicGreet1: 'Thank you! It is always helpful to know when you are ready to move on. What questions can I answer for you now?',
  newTopicGreet2: 'It is always great to start again. Ask me any question!',
  newTopicGreet3: 'Of course, I would love to start again. What can I do for you now?',
  newTopicGreet4: 'Of course, I am ready for new challenges. What can I do for you now?',
  newTopicGreet5: 'Yes, let\'s change the topic. What are you thinking?',
  newTopicGreet6: 'Don\'t worry, I am happy to try something new. What questions can I answer for you now?',
  newTopicGreet7: 'Ok, I am ready! Thank you for setting up. What should we know?',
  newTopicGreet8: 'Thank you for refreshing! Do you have a new topic?',
  newTopicGreet9: 'Understood, let\'s start again from the beginning. What should I discuss next?',
  newTopicGreet10: 'Next! What can I do for you?',
  newTopicGreet11: 'Ok, I am ready for a new topic. What should we learn together?',
  newTopicGreet12: 'Understood, please continue! Thank you for letting me know. What can I help?',
  newTopicSugg1: 'Teach me a new word',
  newTopicSugg2: 'How to set achievable goals?',
  newTopicSugg3: 'Teach me information about the moon landing',
  newTopicSugg4: 'What is the smallest mammal in the world?',
  newTopicSugg5: 'Which is the deepest ocean?',
  newTopicSugg6: 'How many hours are in a year?',
  newTopicSugg7: 'I want to learn a new skill',
  newTopicSugg8: 'Make me laugh',
  newTopicSugg9: 'What is the news?',
  newTopicSugg10: 'Show me inspiring quotes',
  newTopicSugg11: 'Give me a joke',
  newTopicSugg12: 'I need help with homework',
  newTopicSugg13: 'Search for non-fiction works',
  newTopicSugg14: 'Inspire me!',
  newTopicSugg15: 'Show me a cooking recipe',
  newTopicSugg16: 'How to make a budget?',
  newTopicSugg17: 'Teach me a new word',
  newTopicSugg18: 'What is the weather like?',
  newTopicSugg19: 'I want to learn a new skill',
  newTopicSugg20: 'How did the universe begin?',
  newTopicSugg21: 'Why do humans need to sleep?',
  newTopicSugg22: 'How to make a cake?',
  newTopicSugg23: 'Why are flamingos pink?',
  newTopicSugg24: 'How does 3D work?',
  newTopicSugg25: 'How were the pyramids built?',
  newUserGreet: 'Welcome! I am Bing and I can use AI to complete many tasks such as helping you find the perfect gift, learning about the ocean, or exploring new music. Let me know what you want to know!',
  newUserSugg1: 'Write a song',
  newUserSugg2: 'Play rock paper scissors',
  newUserSugg3: 'Search the web',
  repeatUserGreet: 'Nice to meet you again! Let\'s continue the conversation. How are you?',
  repeatUserSugg1: 'Play a small game',
  repeatUserSugg2: 'Suggest a good book',
  repeatUserSugg3: 'Give me a puzzle',
  creativeGreet: 'Good! It will be fun. What are you thinking?',
  balancedGreet: 'Ok, let\'s find answers and chat with the day. What can I do for you?',
  preciseGreet: 'Thank you for chatting. What can I do for you today?',
  creativeSugg1: 'Tell me about constellations',
  creativeSugg2: 'Give me a question you want to ask',
  creativeSugg3: 'Write a love letter to a Storm',
  balancedSugg1: 'Write a poem about popcorn',
  balancedSugg2: 'Where can the stars be seen nearby?',
  balancedSugg3: 'I need some advice',
  preciseSugg1: 'I need help doing research',
  preciseSugg2: 'When is the next solar eclipse',
  preciseSugg3: 'Tell me about the 22nd president',
  close: 'Close',
  newTopicPrompt: 'With new topics, you can start a completely new conversation with Bing about any topic',
  typingIndicatorStopRespondingAriaLabel: 'Stop responding',
  loading: 'Loading',
  canceling: 'Canceling',
  welcomeLearnSegment0: 'Bing is supported by AI, so accidents and errors may occur. Be sure to check the facts, and',
  welcomeLearnSegment1: 'Let\'s learn together. Bing is supported by AI, so accidents and errors may occur. Be sure to check the facts, and',
  welcomeLearnSegment2: 'Share feedback',
  welcomeLearnSegment3: 'So we can learn and improve!',
  welcomeLearnMessage: 'Bing is supported by AI, so accidents and errors may occur. Please share feedback so that we can improve!',
  welcomeLearnMessage2: 'Bing Chat processes the words you enter into Windows Copilot to create AI-based responses and improve your experience in Windows.',
  welcomeLearnFeedbackSubstitute: 'Share feedback',
  adsDisclaimer: 'Ads are not targeted based on workspace recognition or chat history. {0}.',
  adsDisclaimerMobileTitle: null,
  adsDisclaimerLearnMoreLink: 'More',
  actionBarSuspendConvPlaceHolder: 'Texting has been disabled for pending accounts',
  actionBarNewlineTooltip: 'Use Shift+Enter to create a line break for longer messages',
  notiReConnect: 'Error.',
  notiChatEnd: 'Chat topic has ended.',
  notiRestartChat: 'Start a new topic within {0} hours',
  notificationAttemptingToReconnect: 'Trying to reconnect...',
  notificationProcessing: 'Trying to connect, please wait',
  notificationLostConnection: 'Sorry, your connection seems to have been disconnected.',
  notificationLostConnectionCta: 'Would you like to try reconnecting?',
  sydneySapphireCopyToClipboardText: 'copied to the clipboard.',
  sydneySapphireUpsellContent: 'Get the new Bing app with AI now!',
  sydneySapphireWelcomeText: 'Welcome back! Here are some things on this page.',
  sydneySapphireConsentTitle: 'Continue to use the New Bing Up Browser',
  sydneySapphireConsentMessage: 'Allow Microsoft to access your browser web content to personalize your experience better with AI-created summaries and Bing\'s new hotspot features. Learn more about More information',
  sydneySapphireConsentConfirmText: 'Confirm',
  sydneySapphireConsentDenyText: 'from',
  sydneySapphireSummarizeSuggestionShip: 'summarize',
  sydneySapphireExplainSuggestionShip: 'Explain',
  sydneySapphireKeyTakeawaysSuggestionShip: 'Key points',
  sydneySapphireGenerateSummaryMessage: 'Create a summary of this page',
  sydneySapphireGPT4Greet: 'Great! GPT-4 is here 🎉. While creative, responses may be slower. What\'s your idea?',
  typingIndicatorStopStreamingAriaLabel: 'Stop streaming',
  sydneyCarouselCollapse: 'collapse',
  sydneyCarouselTitle: 'Recent chat topics',
  messageActionsCopy: 'copy',
  messageActionsCopying: 'Copying',
  messageActionsCopied: 'copied',
  messageActionsCopyError: 'error',
  messageActionsReport: 'Report',
  tooltipPositive: 'like',
  tooltipNegative: 'dislike',
  tooltipShare: 'Share',
  tooltipMore: 'More',
  tooltipSendToPhone: 'Continue on phone',
  codeDisclaimer: 'This code is created by AI. Consider and use carefully. For more information, please {0}.',
  codeDisclaimerLinkLabel: 'Visit our FAQ',
  exportTitle: 'Export',
  exportTextTitle: 'Download as text (.txt)',
  exportPdfTitle: 'Download in PDF format (.pdf)',
  exportWordTitle: 'Download in Word format (.docx)',
  exportWordOnlineTitle: 'Export to Word Web App',
  exportExcelTitle: 'Download in Excel format (.xlsx)',
  exportExcelOnlineTitle: 'Export to Excel Web App',
  exportToastViewButtonLabel: 'View',
  exportSuccessToastTitle: 'exported. Some formats and images may not be exported.',
  exportErrorToastTitle: 'Export failed',
  exportLoadingToastTitle: 'Exporting...',
  exportedFileUserTitle: 'User',
  exportedFileBotTitle: 'Bing',
  feedbackExportButtonAriaLabel: 'Export',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  tooltipExport: 'Export',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  exportOnlineWordButtonLabel: 'Word Online',
  exportLocalWordButtonLabel: 'Download',
  exportTableToExcelButtonTooltip: 'Open in browser',
  mobileUpsellMessage1: 'Scan this QR code to continue this conversation on the Bing mobile app',
  mobileUpsellTitle1: 'Continue on phone',
  sydneySapphireUpsellConsentTitle: 'Should we continue the conversation from the desktop?',
  sydneySapphireUpsellConsentMessage: 'You have an active Bing chat on other devices. Do you want to continue this conversation?',
  sydneySapphireUpsellConsentConfirm: 'Yes',
  sydneySapphireUpsellConsentDeny: 'No, thank you',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: 'Click',
  actionBarKeyboardHint: 'Input',
  feedbackShareAnswer: 'See this Bing answer',
  feedbackShareGenerated: 'See what I created using Bing',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: 'Show all tones',
  feedbackHideTonesButtonAriaLabel: 'Hide all tones',
  feedbackHidePreciseToneButtonAriaLabel: 'Hide precise',
  feedbackShareErrorToast: 'Sharing failed.',
  fileUploadFlyoutInputboxAriaLabel: 'Paste web page URL',
  fileUploadFlyoutTitle: 'Add text file',
  fileUploadFlyoutUploadButtonLabel: 'Upload from this device',
  fileUploadGenericErrorMessage: 'Sorry - Your upload seems to have failed. Please try again',
  preview: 'Preview',
  toneSelectorDescription: 'Select dialogue style',
  toneSelectorCreative: 'creative',
  toneSelectorCreativeModifier: 'More',
  toneSelectorBalanced: 'balanced',
  toneSelectorBalancedModifier: 'More',
  toneSelectorPrecise: 'precise',
  toneSelectorPreciseModifier: 'More',
  toneSelectorMoreCreative: 'More\\r\\n Creative',
  toneSelectorMoreBalanced: 'More\\r\\n Balanced',
  toneSelectorMorePrecise: 'More\\r\\n Precise',
  toneSelectorFaster: 'More',
  toneSelectorWithGPT4: 'GPT-4',
  notificationMaxTurnsPerDay: 'Sorry, you have reached the limit of messages you can send to Bing within 24 hours. Please check back later!',
  notificationMaxTurnsPerConversation: 'Sorry, this conversation has reached its limit. Use the Sweep button to clear this content and chat more with More.',
  notificationMaxTurnsForMuidUsers: 'You have reached the limit of your conversation today.',
  notificationMaxTurnsForInPrivateUsers: 'you have reached the limit of the InPrivate session. Open a non-InPrivate window to continue chatting',
  notificationUnauthorizedMuidUsersCta: 'Log in to continue your chat.',
  notificationChatEnterMuidUsers: 'Log in to ask more questions about More and conduct a longer chat.',
  muidUsersTermsCond1: 'Start by clicking Start and continue interacting with Bing, which means you accept',
  muidUsersTermsCond1Inline: 'By continuing to interact with Bing, you will accept',
  muidUsersTermsCond2: 'and confirm that you have viewed',
  muidUsersPrivacyStatement: 'Privacy statement',
  muidUsersTermsOfUse: 'Terms of use',
  muidUserGetStartedText: 'Get started',
  muidUserContinueText: 'Continue',
  exportedFileUserTitle: 'User',
  exportedFileBotTitle: 'Bing',
  feedbackExportButtonAriaLabel: 'Export',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  tooltipExport: 'Export',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  exportOnlineWordButtonLabel: 'Word Online',
  exportLocalWordButtonLabel: 'Download',
  exportTableToExcelButtonTooltip: 'Open in browser',
  mobileUpsellMessage1: 'Scan this QR code to continue this conversation on the Bing mobile app',
  mobileUpsellTitle1: 'Continue on phone',
  sydneySapphireUpsellConsentTitle: 'Should we continue the conversation from the desktop?',
  sydneySapphireUpsellConsentMessage: 'You have an active Bing chat on other devices. Do you want to continue this conversation?',
  sydneySapphireUpsellConsentConfirm: 'Yes',
  sydneySapphireUpsellConsentDeny: 'No, thank you',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: 'Click',
  actionBarKeyboardHint: 'Input',
  feedbackShareAnswer: 'See this Bing answer',
  feedbackShareGenerated: 'See what I created using Bing',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: 'Show all tones',
  feedbackHideTonesButtonAriaLabel: 'Hide all tones',
  feedbackHidePreciseToneButtonAriaLabel: 'Hide precise',
  feedbackShareErrorToast: 'Sharing failed.',
  fileUploadFlyoutInputboxAriaLabel: 'Paste web page URL',
  fileUploadFlyoutTitle: 'Add text file',
  fileUploadFlyoutUploadButtonLabel: 'Upload from this device',
  fileUploadGenericErrorMessage: 'Sorry - Your upload seems to have failed. Please try again',
  preview: 'Preview',
  toneSelectorDescription: 'Select dialogue style',
  toneSelectorCreative: 'creative',
  toneSelectorCreativeModifier: 'More',
  toneSelectorBalanced: 'balanced',
  toneSelectorBalancedModifier: 'More',
  toneSelectorPrecise: 'precise',
  toneSelectorPreciseModifier: 'More',
  toneSelectorMoreCreative: 'More\\r\\n Creative',
  toneSelectorMoreBalanced: 'More\\r\\n Balanced',
  toneSelectorMorePrecise: 'More\\r\\n Precise',
  toneSelectorFaster: 'More',
  toneSelectorWithGPT4: 'GPT-4',
  notificationMaxTurnsPerDay: 'Sorry, you have reached the limit of messages you can send to Bing within 24 hours. Please check back later!',
  notificationMaxTurnsPerConversation: 'Sorry, this conversation has reached its limit. Use the Sweep button to clear this content and chat more with More.',
  notificationMaxTurnsForMuidUsers: 'You have reached the limit of your conversation today.',
  notificationMaxTurnsForInPrivateUsers: 'you have reached the limit of the InPrivate session. Open a non-InPrivate window to continue chatting',
  notificationUnauthorizedMuidUsersCta: 'Log in to continue your chat.',
  notificationChatEnterMuidUsers: 'Log in to ask more questions about More and conduct a longer chat.',
  muidUsersTermsCond1: 'Start by clicking Start and continue interacting with Bing, which means you accept',
  muidUsersTermsCond1Inline: 'By continuing to interact with Bing, you will accept',
  muidUsersTermsCond2: 'and confirm that you have viewed',
  muidUsersPrivacyStatement: 'Privacy statement',
  muidUsersTermsOfUse: 'Terms of use',
  muidUserGetStartedText: 'Get started',
  muidUserContinueText: 'Continue',
  threadsSharedOnDate: 'Shared on {0}',
  threadsMore: 'More',
  threadsExportPanelTitle: 'Choose format',
  threadsExportPanelAriaLabel: 'Choose',
  threadsAADMSARedirectConfirm: 'Switch user configuration',
  threadsAADMSARedirectDescription: 'You are using your Microsoft account to save your chat history. The next time you log in with your personal account, it will appear here.',
  threadsCancel: 'Cancel',
  threadsChatHistory: 'Chat history',
  threadsConfirm: 'Confirm',
  threadsDaysAgo: '{0} days ago',
  threadsDefaultChatName: 'Untitled chat',
  threadsDelete: 'delete',
  threadsEdit: 'Rename',
  threadsLoad: 'Chat',
  threadsMinimizeRecent: 'Minimize recent chats',
  threadsMinimizeSaved: 'Minimize saved chats',
  threadsPreview: 'Preview',
  threadsPreviewText: 'Jump back to recent chat',
  threadsRecentTitle: 'Recent activity',
  threadsRecentTitleShort: 'Recently used',
  threadsSavedTitle: 'saved',
  threadsSeeAllRecent: 'See all recent chats',
  threadsSeeAllSaved: 'See all saved chats',
  threadsTitle: 'chats',
  threadsTitleForFlux: 'Menu',
  threadsYesterday: 'Yesterday',
  threads2TLastAccessed: 'Last response time',
  threads2TInfoChanged: 'This information may have been changed, because',
  threads2TArchivedText: 'Screenshot',
  threads2TReloadDescription: 'Click Reload to display the latest information from the web',
  threads2TFailedSearch: 'See the latest Bing.com',
  threads2TReload: 'Search Bing.com',
  injectedActionCardTitle: 'Chat about this page?',
  injectedActionCardNewTopicTitle: 'Start a new conversation about this page?',
  injectedActionCardConfirm: 'send',
  injectedActionCardDeny: 'dismiss',
  webPageContextPrefix: 'visited the web page',
  useGPT4SwitchLabel: 'GPT-4',
  zeroInputSuggestionFallback1: 'Which coffee grinder is highly rated?',
  zeroInputSuggestionFallback2: 'For a family of six on a tight budget, which three car models would be prioritized?',
  zeroInputSuggestionFallback3: 'Write a joke that my colleagues will find funny',
  zeroInputSuggestionFallback4: 'What is the next trend? Where should I shop to find it?',
  zeroInputSuggestionFallback5: 'Write a unique fable about a fish and a frog searching for love',
  zeroInputSuggestionFallback6: 'Create a chart to help me plan meals for the next two weeks',
  zeroInputSuggestionFallback7: 'Create a slogan for a new satirical social media platform',
  zeroInputSuggestionFallback8: 'Design a poster for a cafe with a sunset and maximize the use of space',
  zeroInputSuggestionFallback9: 'Draw a polar bear sunbathing on an iceberg in an impressionistic style. It should also be drinking lemonade',
  zeroInputSuggestionFallback10: 'Write an essay on the history of feminist literature and provide me with five writing tips to proceed',
  notificationMaxTurnsAndOpenEdge: 'You have reached the dialogue limit. To continue chatting, ',
  notificationMaxTurnsAndOpenEdgeCta: 'Open in Microsoft Edge'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 设置未登录用户的 codexMUIDUser 为 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Bing Chat Enterprise'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = 'AI Web Copilot'
  _w['_sydConvTranslation']['inputRaiLabel'] = 'Dữ liệu cá nhân và công ty của bạn được bảo vệ trong cuộc trò chuyện này'
}