/* eslint-disable */
_w["_sydBaseSpecifierPrefix"] = "rms-answers-SharedStaticAssets-";
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableOpenEdgeNotification: false,
  enableSuppressSigninMessage: false,
  enableBackgroundFix: true,
  hideMuidUpsell: false,
  usePill: true,
  enableSydTigerAns: true,
  enableTigerEnhancedPrompt: false,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  enableDlBing: false,
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  enableClearConv: false,
  disableSydGhosting: false,
  isSydCorpnet: false,
  hideSydFSC: false,
  sydOptionSets: 'gcccomp,agicert,iyjbexp,izusrprmpt',
  sydBalOpts: 'fluxhint,glfluxv13',
  sydCrtOpts: 'fluxhint,fluxv13',
  sydPrcOpts: 'fluxhint,fluxv13',
  voiceSrOptions: '',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'gbacf,divkorbl2p,emovoicecf,tts3cf,crtrgxnew,inochatv2,wrapnoins,norbingchrome,sydconfigoptc,178gentechs0,824fluxhi52s0,0825agicert,0901usrprmpt,821fluxv13hint,727nrprdrs0',
  sydBaseUrl: location.origin,
  compSydBaseUrl: '',
  isCompliantSydneyEndpointEnabled: false,
  isBingChatForEnterprise: false,
  isBingChatForSchools: false,
  isBingChatForFaculty: false,
  enableMessageExtensionsForBizChat: false,
  enableUserFeedbackDefaultConsent: false,
  isFeedbackEnabled: true,
  isSharingDiagnosticsEnabled: true,
  isOcvInAppFeedbackSdkEnabled: false,
  isOcvTestEndpointEnabled: false,
  compliantSydneyFlights: '',
  useAccountLinkingForConversationLimitUpsell: false,
  includeSubstrateToken: false,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enablePassingExperienceType: false,
  enableHttpPostForIFrameAnswers: false,
  enableNewECC: false,
  enableDotsAnimation: false,
  enableBceBcbToggle: false,
  noInitOpts: false,
  overrideSydOptions: false,
  removeDeepleo: false,
  enableSydNativeIntegration: false,
  enableSydSuperAppIntegration: false,
  enableSydSuperAppNativeVoice: false,
  sydSappNewConvTooltipLogic: false,
  enableSydSappFeedbackButton: false,
  sydneySapphireLogLevel: 5,
  enableSydSwiftKeyIntegration: false,
  enableSydDelayLocationRequest: false,
  enableSydMicrosoftLauncherIntegration: false,
  enableSapphireSydVoiceExp: false,
  enableSydneySapphireBridgeMocks: false,
  enableSuperAppKeyboardPopup: false,
  sydneySuperAppFeatures: '',
  getLocationDataFromHeader: '',
  sydneySwiftKeyFeatures: '',
  sydneyMicrosoftLauncherFeatures: '',
  isSappMobileOptimizedOn: false,
  enableSapphireContextRegistration: false,
  enableSapphireContextRegistrationIAB: false,
  enableSapphireContextRegistrationConsent: false,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableEdgeMobileNativeTTS: false,
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  enableInPrivateUserMode: false,
  sydUrlPart: '',
  compSydUrlPart: '',
  enableCafeForCompliantSydney: false,
  cafePathSuffixForCompliantSydney: '',
  compliantSydOptionsSets: '',
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  zip: '90012',
  timezoneoffset: '8',
  enableTimezoneOffsetFromJS: false,
  dma: 0,
  lat: '78.4156',
  long: '-101.4458',
  language: 'Chinese (China)',
  userMailId: '123456@hotmail.com',
  username: 'Harry-zklcdc',
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  isVisualParityRun: false,
  enableSydAjax: false,
  moveOnlySydXAnswers: true,
  enable1TCibSlot: false,
  enableSydOverlay: false,
  enableSydX1T: true,
  enableSydTestCache: false,
  hideSydMic: false,
  enableSydCarousel: true,
  fromNoResults: false,
  sydTestCacheMsg: '',
  sydTestMockShareId: '',
  sydTuringSuggestionsMocked: false,
  traceId: randomLowercaseString(32),
  extraSappOptions: '',
  extraEdgeOptions: 'eredirecturl',
  extraBceOptions: '',
  enableSydMic: true,
  carouselQueries: '',
  sydCarPropQuery: false,
  enableSydShare: true,
  enableMessageShareableSignal: false,
  enableTigerCachedAttr: false,
  enableSydCarouselHistory: false,
  enableSydCookLoc: true,
  enableSQMsg: true,
  enable161Feats: true,
  addDv3Opt: true,
  addGenContentv3Opt: false,
  hideSydReconnect: false,
  enableErrorTelemetry: true,
  enableSemSerpNoCache: false,
  checkCreatorAnsFor1T: true,
  enableSydStrictRedirect: false,
  enableAnsCardSuffix: true,
  enableSydStaticAdsLink: false,
  removeDSAT: true,
  enableShortOpt: false,
  enableSpeechExperimentalFeatures: true,
  enableSydAjaxReset: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  cdxFeats: '',
  enableSecureUpdateConversation: false,
  enableSecureSendFeedback: false,
  disableSecureUpdateConversation: false,
  disableSecureSendFeedback: false,
  enableSemSerpShare: false,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableRotateDisclaimer: false,
  enableRotateWelMsg: false,
  enableDM: true,
  enableSydImageCreate: true,
  disableCibNotificationStyleUpdate: false,
  enableSecureConnect: true,
  enableInstanceAffinity: false,
  enableToneCook: true,
  toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSpeechChatDataAfterPhrase: false,
  enableSpeechEarconOnInput: false,
  enableTTSOnSuggestionAfterVoice: false,
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: false,
  enableSpeechFateTTSStop: true,
  enableSpeechGetUserMedia: false,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechInputWhileRequestIsPending: false,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableSpeechReopenMic: false,
  enablePersistentToneSelector: false,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableTelemetryPrivacy: false,
  isAccountLinkedWithActiveAAD: false,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
  enableMaxTurnsFromBackend: false,
// 设置已登录账号的聊天对话次数
  maxTurnsPerConversation: 30,
// 设置未登录账号的聊天对话次数
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  enableSigninTurnFix: true,
  enableAmberTurnPerConversation: false,
  amberTurnPerConversation: 0,
  enableAdSlugsDesktop: false,
  disResetTT: false,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableEmbeddedPerf: false,
  enableE2EPerf: false,
  enableAdSlugsMobile: true,
  enableCreatorShare: false,
  enablePuidOvr: false,
  enableUnauthRedir: true,
  enableSydSafeSearch: false,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  userPriorityLevel: 999,
  enableUserPriorityLevel: false,
  enableMMAnsType: true,
  enableStreamSyntheticTextResponses: true,
  enableToneCookExpiry: false,
  syntheticStreamSpeed: 55,
  disableShareWithNoMargin: false,
  enableMobileShareAnchorBottom: true,
  disableTabletScroll: false,
  disableTabletScrollOut: false,
  disableFocusedTabletScrollOut: false,
  disableTouchDesktopScroll: false,
  disableDesktopScroll: false,
  enableSuggEndFix: false,
  enableBalancedSerp: false,
  enableAlwaysCreativeSerp: false,
  enableBalancedSerpLog: false,
  enableCreativeLandingPage: false,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableThreadShareWithoutRenderCardRequest: false,
  enableSuperOptionsSets: false,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableOneClickCopy: false,
  enableReorderCopiedTextReferences: false,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableRichTextPaste: false,
  enablePasteMarkdownTable: false,
  enablePasteMath: false,
  enableInlineFeedback: true,
  enableInlineFeedbackV2: false,
  enableInlineFeedbackV21: false,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableFeedbackMenuOverflow: false,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  isSapphireClient: false,
  enableOptimizedStreaming: false,
  enableSydneySapphireUpsellVisualSearch: false,
  enableSydneySapphireUpsellMessageActions: true,
  enableSydneySapphireUpsellEndOfChat: false,
  enableSydneySapphireUpsellContinueConversation: false,
  sydneySapphireUpsellTreatment: 0,
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://aka.ms/cntphup',
  enableConvModeSwitchAjax: false,
  enableSetToneFromUrl: true,
  suppressKnobCreative: 0,
  suppressKnobBalanced: 0,
  suppressKnobPrecise: 0,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSuppressTones: false,
  enableShoppingHelperPersonaDemo: false,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  enableDevFormOverrideForAds: false,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  codexMUIDUser: false,
  enableAutosuggestMetrics: false,
  enableCodexMuidConsentTop: false,
  enableCodexMuidConsentExplicit: false,
  enableCodexMuidConsentImplicit: false,
  enableSydneyGetMessagesHub: false,
  bypassConsentCheck: false,
  enableFixCodeXAsBug: true,
  enableChatIconClickable: false,
  enableChatQueryClickable: false,
  enableChatQueryClickableV2: false,
  enableChatQueryClickableV3: false,
  enableChatQueryClickableV4: false,
  enableCreatorSendQueryWhenShowConvQuery: true,
  enableCodexWinBotMessage: false,
  enableCodexWin: false,
  enableThreads: true,
  enableThreadsCF: false,
  codexWinEnableCustomGreeting: false,
  codexWinGreetingCustomString: '',
  codexWinCurrentTurn: 0,
  enableSkipContentOriginCheck: false,
  enableSydneySimpleWelcomeScreen: false,
  enableMobileOneClickShare: false,
  enableMobileOneClickShareV2: true,
  enableShareQuestionWithResponse: false,
  enableShareQuestionTitlePrefix: false,
  enableShareInlineAdsIframe: false,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableShareWholeThreadMockUp: false,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableWholeThreadPerformanceFix: false,
  enableShareCurrentThreadMessagesfromAPI: true,
  enableDisposeOrphanedHosts: false,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enable2TTest: false,
  enableSydBeacon: true,
  enableShareOnHostMessage: false,
  enableVisualSearch: true,
  enableFileUpload: false,
  aimgut: false,
  removeCameraInputForVisualSearch: false,
  dVSOC: false,
  eifpiab: false,
  emwc: false,
  evssid: false,
  evscamprd: false,
  vscamprdname: '',
  eufte: false,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  enableChatCoach: '',
  suppressAlsoTryWhenEnableSydCarousel: false,
  suppressPoleRSWhenEnableSydCarousel: false,
  disablePassBotGreetingInContext: true,
  enableHoverCardOnLearnMorePills: false,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableInvisibleCaptchaChallenge: false,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  enableCibOverlayForKnowledgeCard: false,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: false,
  enableCopyButtonInstrumented: true,
  enableWowCDSSurvey: false,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableMessageExportLocalExcel: false,
  enableTableBarFlatActions: false,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableBotMessageActionsBar: false,
  enableShorterOnlineExportSuccessToastDuration: false,
  enableDirectlyOpenExportOnlineLink: false,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: false,
  enableLimitToAadOnlineExport: true,
  enableAdsRedirectLinkForTextMessage: false,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableCopyHtmlWithHighlightedCode: false,
  enableExportPdfWithAnswerScreenshot: false,
  enableExportDocxWithAnswerScreenshot: false,
  enableGetChats: true,
  enableLibrariesSplitImport: false,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
  enableCssSplitConvModeOnClick: false,
  enableFlux3P: false,
  enablePluginsByTone: false,
  enableDelayShowConvEvent: false,
  disableWelcomeScreen: true,
  enableWelcomeScreenV2: true,
  enableChatFRE: false,
  enableChatFRE2: false,
  enableChatFRECSS: false,
  enableChatFREAutoScroll: false,
  enableNewTables: false,
  codexTableVersion: 1,
  enableBufferMessage: false,
  enableBufferDots: false,
  enableTestDailyLimit: false,
  enableTestTurnLimit: false,
  enableWebPageContextMessages: false,
  enableCodexPluginb: false,
  enableBICHistory: true,
  enable2TScreenshot: false,
  enable2TScreenshotSnR: false,
  enableWelcomeScreenAIRolesV1ForMobile: false,
  enableNewAutoSuggestEndPoint: false,
  enableFixChatScopeActive: false,
  enableHideConvMode: false,
  shouldUseSydneyDynamicCIB: false,
  enableRenderCardRequestIMSearchParams: true,
  enableCodexTesthooks: false,
  flux3PPluginList: '',
  enableTypingIndicatorAnimation: false,
  typingIndicatorAnimationDuration: 1000,
  enableTypingIndicatorDemoteStyle: false,
  enableMessagePrivacy: false,
  disableTooltip: false,
  enableNewlineTooltip: false,
  enableCloseShareOnClickOutside: false,
  enableSapphireFullScreenMode: false,
  enableSapphireSydneyNativeShare: false,
  enableTypingIndicatorForSerpSlotCreator: false,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableUpdateProfile: false,
  enableTypewriter: true,
  enableConfirmPromptSingleDeleteThread: false,
  enableSydneySapphireKeyboardFirst: false,
  enableSydneySapphireGPT4Treatment1: false,
  enableSydneySapphireGPT4Treatment2: false,
  enableSydneySapphireSuggestions: false,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableSaharaStream: false,
  enableFaviconsV2: false,
  enableFaviconsAutoRefresh: false,
  enableUserIpAddress: true,
  enableActionBarV2: true,
  enableLooseMessageDensity: false,
  enableSuggestionItemEnterAnimation: false,
  enableKatexScroll: true,
  enableSpeechDictationBridgeMode: false,
  bypassMicPermissionsQuery: false,
  enableSkipContentOriginValidation: false,
  enableEmptyThreadTime: false,
  enableLinkPreviewCarousel: false,
  useFakeDataForLinkPreviewCarousel: false,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: false,
  enableUpdateUserMessageId: true,
  enableUserMessageIdConsistency: false,
  enableCreativeToneIgnoreAndDefaultToBalanced: false,
  enablePreciseToneIgnoreAndDefaultToBalanced: false,
  enablePluginPanelFre: false,
  enableSapphireSerpSuggestionChipClick: false,
  enableThreadsTestData: false,
  enableRenderIframeCardRequest: false,
  enableBackendExportService: false,
  enableExternalSpeechIconAnimation: false,
  enableMobileFirstClickShare: true,
  enableInlinePersonalizationConsent: false,
  personalizationInlineConsentTurn: 0,
  enableEduStarterMessage: false,
  enableEduStarterMessageAnimation: false,
  enableSpeculativeMode: false,
  enableNoBingSearchResponseBackground: false,
  enableNoSearchPluginMetaMessage: false,
  enableMobileAnchoredScrollOnResponse: false,
  enableInlineAdsDynamicWidth: false,
  enableExportPdfWithRichFormat: false,
  enableAttributionImages: false,
  enableAttributionImagesWhenAdsPresent: false,
  enableAttributionImagesCarousel: false,
  enableAttributionImagesClickthrough: false,
  enableNewConversationActivate: false,
  enableFastChatLoadAnimation: false,
  enableShareInThreadsHeader: true,
  enableThreadsConsent: false,
  enableDeleteSingleConversationMemory: false,
  enableThreadsTopRightButton: false,
  enablePluginsTopRightButton: false,
  enableSapphireSydCameraFirst: false,
  enableStableAutosuggestion: false,
  enableSydneyFSCTranslationSrc: false,
  enableBceMuidConsent: false,
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  enableSydSuperAppAnchoredScroll: false,
  enable2TQueryConfigsOnSerpLoad: false,
  isMobileHost: false,
  enableSERPHideShowConv: false,
  enableAjaxBundlePostLoad: false,
  PLoadIID: 'SERP.5912'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: 'If you have a question, just ask me....(Shift + Enter = line break, "/" trigger prompt)',
   actionBarAriaLabel: 'Ask Bing',
   actionBarComposeButton: 'New theme',
   actionBarNewChatButtonDesktop: 'Start a new chat',
   actionBarNewChatButtonMobile: 'New chat',
   actionBarOngoingConvPlaceholder: 'Type message',
   attachmentLoading: 'Loading attachment',
   notiUpdateBrowser: 'Sorry, this version of the browser is not supported. Please update your browser to the latest version to continue. ',
   bufferMessage1: 'Im using it, please wait',
   bufferMessage2: 'Please wait',
   bufferMessage3: 'Take a moment to think...',
   captchaTitle: 'Verify identity',
   captchaDescription: 'To continue, enter characters in the following image.',
   captchaPlaceholder: 'Enter character...',
   captchaPlaceholderError: 'Sorry, please try again. ',
   next: 'Next',
   cancel: 'cancel',
   feedbackAccessed: 'Access time',
   feedbackSource: 'Source: Conversation with Bing',
   feedbackShareConversationQuery: 'Whats the new version of Bing?',
   feedbackThanksMessageV2: 'Thank you for your feedback. Please restart or refresh the page. ',
   messageLearnMore: 'Learn more:',
   messageReference: 'reference',
   messageReferences: 'references',
   messagePrivacyLabel: 'Your personal and company data is protected in this chat',
   inputRaiLabel: '',
   letsChat: 'Lets chat',
   pause: 'pause',
   play: 'Play the game',
   speechFailedRecognitionError: 'Sorry, I cant listen to you because the speech server is down, please try again later.',
   speechListening: 'Im listening...',
   speechLoading: 'Waiting for audio...',
   speechMediaNotReachableError: 'Sorry, I cant listen to you because you dont have a microphone available. ',
   speechNoPermissionError: 'You need to enable the microphone for me to hear you.',
   speechAudioPlaybackError: 'An error occurred. ',
   startOver: 'Restart',
   stop: 'stop',
   welcomeContainerFAQs: 'Frequently Asked Questions',
   welcomeContainerPrivacyStatement: 'Privacy',
   welcomeContainerUseTerms: 'Terms',
   welcomeContainerLearnMore: 'Learn more',
  welcomeMessageItemContent1:  'What can I cook for my picky kid who only eats orange food?',
  welcomeMessageItemContent2:  'What are the pros and cons of  the top 3 best-selling pet vacuums?',
  welcomeMessageItemContent3: 'Простовання п',
  welcomeMessageItemTitle1:  'Ask a complex question🧐',
  welcomeMessageItemTitle2:  'Get a better answer🙌', 
  welcomeMessageItemTitle3:  'Get creative inspiration🎨',
  welcomeMessageItemLabel4: 'Whats new in more ideas:',
  warmWelcomeTitle:  'Welcome to the new Bing',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel:  'Welcome to new Bing',
  welcomeSubtitleText:  'AI-powered online assistant', 
  workToggleDescription: 'And what your results include',
  feedbackFirstMessage:  'Sorry didnt help you. Can you elaborate on what you didnt like?',
  feedbackPromptMessage:  'Thanks for the reminder. Please provide feedback so that the Bing team can review it. ',
  feedbackPromptGiveFeedback: 'Give feedback',
   feedbackPromptGiveFeedbackAriaLabel: 'Give feedback',
   feedbackPromptReportAConcern: 'Report a problem',
   feedbackPromptPositive: 'Glad you liked this answer!',
   feedbackFormTitleText: 'Why doesnt this work?',
   feedbackFormInputDefaultText: 'Add more details here. To help protect your privacy, please do not include personal information such as your name or email address. ',
   feedbackFormLegalText: 'Is there a legal or policy issue?',
   feedbackFormReportAConcern: 'Report a problem',
   feedbackFormNotificationTitleText: 'Feedback has been submitted',
   feedbackFormNotificationBodyText: 'Thank you for helping Bing improve!',
   feedbackFormThanksMessage: 'Thank you for your feedback!',
   feedbackFormReturnToChatMessage: 'Return to chat',
   serpFeedbackFormTitleText: 'Please help us improve the experience',
   serpFeedbackFormInputDefaultText: 'Enter feedback here. To help protect your privacy, please do not include personal information such as your name or email address. ',
   serpFeedbackFormScreenshot: 'Include this screenshot',
   serpFeedbackFormRadioLike: 'Like',
   serpFeedbackFormRadioDislike: 'dislike',
   serpFeedbackFormRadioConnectionIssues: 'Connection issues',
   serpFeedbackFormRadioSlowResponses: 'Slow response',
   serpFeedbackFormRadioOther: 'Other',
   feedbackFormUnderstandDataSharedText: 'Learn more about what is shared as diagnostic data',
   feedbackFormUserConsentText: 'Share prompt to Copilot, response received from Copilot, and diagnostic data for this interaction?',
   feedbackFormUserConsentYesText: 'Yes',
   feedbackFormUserConsentNoText: 'No',
   feedbackFormPrivacyStatement: 'Privacy Statement',
   feedbackFormPrivacyText: 'After you press "Submit", your feedback will be used to improve Microsoft products and services. Your organizations IT admins will be able to view and manage feedback data. ',
   compliantPositiveFeedbackFormTitleText: 'Submit feedback to Microsoft',
   compliantPositiveFeedbackQuestionText: 'What do you like?',
   compliantPositiveFeedbackDefaultText: 'Please dont provide any personal information.',
   compliantNegativeFeedbackFormTitleText: 'Send detailed feedback to Microsoft',
   compliantNegativeFeedbackCategoryText: 'The content is',
   compliantNegativeFeedbackQuestionText: 'What went wrong?',
   compliantFeedbackThanksText: 'Thank you for submitting feedback on {0}!',
   compliantFeedbackCategoryInaccurate: 'Inaccurate',
   compliantFeedbackCategoryOffensive: 'Offensive or inappropriate',
   compliantFeedbackCategoryOther: 'Other',
   submit: 'submit',
   explore: 'Browse',
   exploreMore: 'Browse more',
   metaInternalSearchQuery: 'Searching for: `{0}`',
  metaInternalLoaderMessage:  'Generating an answer for you...',
  metaInternalImageLoaderMessage: 'Analyzing Image: Privacy Blur Hides Faces in Bing Chat',
  compliantMetaInternalLoaderMessage: 'Generate a safe answer from {0}',
  messageSharedContent:  'Share content',
  clickToView: 'Click to view',
  more: 'more',
  expand: 'Expand',
  welcomeTertiaryTitleText: 'Use the power of AI to find answers from the web, create written content, and more. ',
  actionBarTextInputAriaLabel: 'Ask Bing',
  seeMore: 'See more',
  seeLess: 'Choose a conversation type',
  raiSuggestions: 'What is this?',
  actionBarFileUploadButtonAriaLabel: 'Search in file',
  actionBarStopStreamingAriaLabel: 'Stop streaming',
  actionBarTextInputModeButtonAriaLabel: 'Use keyboard',
  actionBarSpeechInputModeButtonAriaLabel: 'Use microphone',
  actionBarVisualSearchButtonTooltip: 'Add image',
  actionBarVisualSearchButtonAriaLabel: 'Add image to search',
  actionBarVisualSearchCoachMarkTitle: 'New Bing with image',
  actionBarVisualSearchCoachMarkDescription: 'Now you can use images to chat with Bing!',
  actionBarVisualSearchCoachMarkImgAlt:  'Visual search tooltip image',
  actionBarSubmitButtonAriaLabel: 'Submit',
   actionBarCancelSpeechInputButtonAriaLabel: 'Cancel Speech Input/Readout',
   actionBarEditModeButtonAriaLabel: 'Fixed',
   actionBarSpeechBtnStartListeningAriaLabel: 'Use microphone',
   actionBarSpeechBtnStopListeningAriaLabel: 'Stop listening',
   actionBarSpeechBtnStopReadoutAriaLabel: 'Stop reading',
   feedbackLikeButtonAriaLabel: 'Like',
   feedbackDislikeButtonAriaLabel: 'dislike',
   feedbackOffensiveButtonAriaLabel: 'Mark as offensive',
   feedbackCopyButtonAriaLabel: 'Copy',
   feedbackShareButtonAriaLabel: 'Share',
   messageSentAriaLabelPrefix: 'Sent sent',
   messageReceivedAriaLabelPrefix: 'Message received',
   messageReportedOffensiveAndRemoved: 'This message has been deleted because it has been reported for review. ',
   messageAttributionsCollapseBtnAriaLabel: 'Collapse',
  newTopicGreet1: 'Thank you! Its always helpful to know when youre ready to move on. What question can I answer for you now?',
  newTopicGreet2: 'Its always great to start over. Ask me anything!',
  newTopicGreet3:  'Sure, Id love to start over. How can I help you now?',
  newTopicGreet4: 'Of course, Im ready for a new challenge. What can I do for you now?',
  newTopicGreet5:  'Okay, lets change the theme. What are you thinking?',
  newTopicGreet6:  'Dont worry, Im excited to try something new. What question can I answer for you now?',
  newTopicGreet7:  'Okay, Im ready!Thanks for the reset. What should we know?',
  newTopicGreet8:  'Thanks for refreshing! do you have a new topic?',
  newTopicGreet9:  'Got it, lets start over. What should be discussed next?',
  newTopicGreet10: 'Whats next!',
  newTopicGreet11: 'Okay, I ve got a new topic ready. What should we know together?',
  newTopicGreet12: 'Got it, please continue! Thanks for letting me know. How can I help?',
  newTopicSugg1:  'Teach me a new word',
  newTopicSugg2:  'How do I set achievable goals?',
  newTopicSugg3:  'Teach me about the moon landing',
  newTopicSugg4:  'What is the smallest mammal in the world?',
  newTopicSugg5:  'Which is the deepest ocean?',
  newTopicSugg6:  'How many hours are there in a year?',
  newTopicSugg7:  'I want to learn a new skill',
  newTopicSugg8:  'Make me laugh',
  newTopicSugg9:  'Whats the news?',
  newTopicSugg10:  'Show me inspirational quotes',
  newTopicSugg11: 'Tell me a joke',
  newTopicSugg12:  'I need help with homework',
  newTopicSugg13:  'Looking for non-fiction',
  newTopicSugg14: 'encourage me!',
  newTopicSugg15:  'Show me recipe',
  newTopicSugg16:  'How do I create a budget?',
  newTopicSugg17:  'Teach me a new word',
  newTopicSugg18:  'Hows the weather?',
  newTopicSugg19:  'I want to learn a new skill',
  newTopicSugg20:  'How did the universe begin?',
  newTopicSugg21:  'Why do humans need sleep?',
  newTopicSugg22:  'How to make a cake?',
  newTopicSugg23:  'Why are flamingos pink?',
  newTopicSugg24:  'How do holograms work?',
  newTopicSugg25:  'How was the pyramid built?',
  newUserGreet:  'Welcome! Im Bing, and I can use AI to do more, like help you find the perfect gift, learn about the ocean, or discover new music. Tell me what you want to know!',
  newUserSugg1: 'Tell me a joke',
  newUserSugg2: '玩小游戏',
  newUserSugg3: 'Tell me a riddle',
  repeatUserGreet:  'Im glad youre back! What can I do for you?',
  repeatUserSugg1:  'Whats the latest',
  repeatUserSugg2:  'Show me a poem',
  repeatUserSugg3:  'Tell me a joke',
  creativeGreet:  'Lets get creative!Are you thinking about a topic, or are you improvising?',
  balancedGreet:  'Sounds good, we can find a balance between anecdotes and facts. How can I help?',
  preciseGreet: 'Thanks for chatting. Can I help you today?',
  creativeSugg1:  'Tell me a strange fact',
  creativeSugg2:  'Tell my horoscope',
  creativeSugg3:  'Give me a question you want to ask',
  balancedSugg1:  'Write a poem about popcorn',
  balancedSugg2:  'How do bees make honey?',
  balancedSugg3:  'I need help making a plan',
  preciseSugg1:  'Who invented language?',
  preciseSugg2:  'I need help doing research',
  preciseSugg3:  'What makes the earth spin?',
  close:  'close',
  newTopicPrompt:  'With a new topic, you can start a brand new conversation with Bing on any topic',
  typingIndicatorStopRespondingAriaLabel: '停止响应',
  loading:  'loading',
  canceling:  'Canceling',
  welcomeLearnSegment0: 'Bing is powered by AI, so surprises and errors can occur. Make sure to check the facts, and ',
  welcomeLearnSegment1:  'Lets learn together. Bing is powered by AI, so surprises and errors can occur. Make sure to check the facts and ',
  welcomeLearnSegment2: '共享反馈 ',
  welcomeLearnSegment3:  'So that we can learn and improve!',
  welcomeLearnMessage:  'Lets learn together. Bing is powered by AI that can understand and generate text and images, so surprises and errors can occur. Make sure to check the facts, and {0} so that we can learn and improve!',
  welcomeLearnMessage2: 'Bing Chat processes the words you enter in Windows  Copilot to generate AI-powered responses and improve your  experience in Windows. ',
  welcomeLearnFeedbackSubstitute: '共享反馈',
  adsDisclaimer: 'Ads are not targeted based on workspace identity or chat history. {0}。 ',
  adsDisclaimerMobileTitle: null,
  adsDisclaimerLearnMoreLink: '了解更多',
  actionBarSuspendConvPlaceHolder: 'Messaging has been disabled for a pending account',
  actionBarNewlineTooltip:  'Create a line break for a longer message using Shift+Enter',
  notiReConnect:  'Something went wrong. ',
  notiChatEnd:  'The chat topic has ended. ',
  notiRestartChat:  'Start a new topic in {0}  hours',
  notificationAttemptingToReconnect:  'Trying to reconnect...',
  notificationProcessing:  'Trying to connect, please wait',
  notificationLostConnection: 'Sorry, your connection seems to have dropped. ',
  notificationLostConnectionCta:  'Do you want to try to reconnect?',
  sydneySapphireCopyToClipboardText:  'Copied to clipboard. ',
  sydneySapphireUpsellContent:  'Get the new AI-powered Bing app now!',
  sydneySapphireWelcomeText: 'Welcome back! Here are some of the contents of this page. ',
  sydneySapphireConsentTitleText:  'Elevate browsing with the new Bing',
  sydneySapphireConsentMessageText:  'Allow Microsoft to access your browser web content for the purpose of using AI.Generated summaries and new Bings hotspot features better personalize your experience. Learn more',
  sydneySapphireConsentConfirmText: 'Confirm',
   sydneySapphireConsentDenyText: 'Deny',
   sydneySapphireSummarizeSuggestionShip: 'Summarize',
   sydneySapphireExplainSuggestionShip: 'Explanation',
   sydneySapphireKeyTakeawaysSuggestionShip: 'Key points',
   sydneySapphireAskMeaningSuggestionChip: 'What does that mean?',
   sydneySapphireRelevantInformationSuggestionChip: 'Give me relevant information about this',
   sydneySapphireOverviewSuggestionChip: 'Could you provide a brief overview?',
   sydneySapphireGenerateSummaryMessage: 'Generate a summary of this page',
   sydneySapphireContextGreet: 'It looks like you asked about {0}. What do you want to know about this?',
   sydneySapphireGPT4Greet: 'Lets get creative with GPT-4 🎉. While being creative, the response time can be slower. Are you thinking about a topic, or should you branch it out?',
   typingIndicatorStopStreamingAriaLabel: 'Stop streaming',
   sydneyCarouselCollapse: 'Collapse',
   sydneyCarouselTitle: 'Recent Chat Topics',
   messageActionsCopy: 'Copy',
   messageActionsCopying: 'Copying',
   messageActionsCopied: 'Replicated',
   messageActionsCopyError: 'Error',
   messageActionsReport: 'Report',
   tooltipPositive: 'Like',
   tooltipNegative: 'dislike',
   tooltipShare: 'Share',
   tooltipMore: 'More',
   tooltipSendToPhone: 'Continue on phone',
   codeDisclaimer: 'This code is generated by AI. Look carefully and use it. For more information, {0}. ',
   codeDisclaimerLinkLabel: 'Visit our FAQ',
   exportTitle: 'Export',
   exportTextTitle: 'Download as text (.txt)',
   exportPdfTitle: 'Download in PDF (.pdf) format',
   exportWordTitle: 'Download in Word (.docx) format',
   exportWordOnlineTitle: 'Export to Word Web App',
   exportExcelTitle: 'Download in Excel (.xlsx) format',
   exportExcelOnlineTitle: 'Export to Excel Web App',
   exportToastViewButtonLabel: 'View',
   exportSuccessToastTitle: 'File exported. Some formats and images may not be exportable. ',
   exportErrorToastTitle: 'Export failed',
   exportLoadingToastTitle: 'Exporting...',
   exportedFileUserTitle: 'User',
   exportedFileBotTitle: 'Bing',
   feedbackExportButtonAriaLabel: 'Export',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  tooltipExport: '导出',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  exportOnlineWordButtonLabel: '联机 Word',
  exportLocalWordButtonLabel:  'Download',
  exportTableToExcelButtonTooltip:  'Open in browser',
  mobileUpsellMessage1: 'Scan this  QR code to continue this conversation on the mobile Bing app',
  mobileUpsellTitle1:  'Continue on phone',
  visualSearchMobileUpsellLabel: 'Use Bing app on phone',
  mobileUpsellTitle2: 'Use Bing app to take photo',
  mobileUpsellMessage2: 'Scan QR code to take this photo with the Bing app on your mobile device',
  sydneySapphireUpsellConsentTitle:  'Do you want to continue chatting from desktop?',
  sydneySapphireUpsellConsentMessage: 'You have an active Bing chat on another device. Do you want to continue this conversation?',
  sydneySapphireUpsellConsentConfirm: 'Yes',
  sydneySapphireUpsellConsentDeny: 'No, thank you',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: 'click',
  actionBarKeyboardHint: 'input',
  feedbackShareAnswer: 'View this Bing Answer',
  feedbackShareGenerated: 'View what Ive built with Bing',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: 'Show all tones',
  feedbackHideTonesButtonAriaLabel: 'Hide all tones',
  feedbackHidePreciseToneButtonAriaLabel: 'Hide precise',
  feedbackShareErrorToast: 'Sharing failed. ',
  serpfeedback: 'Feedback',
  shareConversation: 'Share the entire conversation',
  speechAuthenticationError: 'Authentication failed. Please try again later. ',
  speechUnknownError: 'An error occurred. ',
  refresh: 'refresh',
  feedbackShareContent: 'Heres the answer I generated using the new Bing, the worlds first AI-powered response engine. Click to see the full answer, and then please give it a try. ',
  fileUploadFlyoutInputboxAriaLabel: 'Paste web page URL',
  fileUploadFlyoutTitle:  'Add text file',
  fileUploadFlyoutUploadButtonLabel:  'Upload from this device',
  fileUploadGenericErrorMessage: 'Sorry - upload seems to fail. Please try again',
  preview:  'preview',
  toneSelectorDescription: 'Choose a conversation type',
  toneSelectorCreative: 'Creative',
   toneSelectorCreativeModifier: 'more',
   toneSelectorBalanced: 'Balanced',
   toneSelectorBalancedModifier: 'more',
   toneSelectorPrecise: 'precise',
   toneSelectorPreciseModifier: 'more',
   toneSelectorMoreCreative: 'more\\r\\n Creative',
  toneSelectorMoreBalanced: 'more\\r\\n Balanced',
  toneSelectorMorePrecise: 'more\\r\\n precise',
   toneSelectorFaster: 'Faster',
  toneSelectorWithGPT4:  'Use GPT-4',
  notificationMaxTurnsPerDay:  'Sorry, youve reached the  24-hour  message limit that you can send to Bing. Please check back soon!',
  notificationMaxTurnsPerConversation: 'Sorry, this conversation has reached its limit. Use the "Sweep" button to clear this content and have more chats. ',
  notificationMaxTurnsForMuidUsers: 'Youve reached todays conversation limit. ',
  notificationMaxTurnsForInPrivateUsers: 'Youve reached the session limit for inPrivate mode. Open a non-inPrivate window to continue chatting',
  notificationUnauthorizedMuidUsersCta: 'Log in to continue your chat. ',
  notificationChatEnterMuidUsers:  'Log in to ask more questions and have longer conversations. ',
  muidUsersTermsCond1:  'You accept by clicking Get Started and continuing to interact with Bing',
  muidUsersTermsCond1Inline:  'By continuing to interact with Bing, you will accept',
  muidUsersTermsCond2:  'And confirm youve viewed',
  muidUsersPrivacyStatement: 'Privacy Statement',
  muidUsersTermsOfUse: 'Terms of Use',
  muidUserGetStartedText: 'Get Started',
  muidUserContinueText: 'Continue',
  welcomeMobSugg1: 'How does Bing use AI?',
  welcomeMobSugg2: 'What else can Bing do?',
  welcomeMobSugg3: 'Whats the latest news in tech?',
  or: 'together',
  notificationResetConversation: 'Sorry, something went wrong. ',
  notificationResetConversationCta:  'Lets start over. ',
  toneSelectorCreativeTooltip:  'Clear the conversation and start an original and imaginative chat',
  toneSelectorBalancedTooltip: 'Clear the chat and start an informative and friendly conversation',
  toneSelectorPreciseTooltip:  'Clear the conversation and start a concise and straightforward chat',
  toneSelectorSuppressedTooltip: 'Not available for the time being. Please try again later!',
  notificationDisengaged: 'Maybe its time for a new topic. ',
  notificationDisengagedCta: '',
  notificationForbidden: 'Sorry, you dont seem to have access to this feature anymore. Please check again in a few days. ',
  notificationTooManyRequests: 'Sorry, the demand is very high right now. Please try again later. ',
  notificationUnauthorized: 'Sorry, you seem to have logged out. ',
  notificationUnauthorizedCta: 'Please log in again. ',
  notificationMessageError: 'The previous message appears to have been interrupted. ',
  notificationSharedTip: 'This dialog\u003cstrong\u003e"{0}"\u003c/strong\u003e has been created in {1} Shared with you',
  mmAnswerPrompt1:  'Ive finally found something for you!Glance. ',
  mmAnswerPrompt2:  'Ive finally found something!Is this what youre looking for?',
  mmAnswerPrompt3: 'Sorry for the confusion, I did find something for you. Here you go!',
  mmAnswerPrompt4: 'Hey! I did find something, is that what you were looking for?',
  mmAnswerPrompt5: 'Look! Ive found something that works for you. ',
  mmAnswerPrompt6:  'Wait, here!Sorry for messing up, take a look. ',
  mmAnswerPrompt7:  'I found the media you wanted!Sorry for the delay. ',
  signInCta: 'Login',
  signInDescription: ' to ask more questions and have longer conversations' ,
  signInDescriptionInPrivate: 'Open a non-inPrivate window for longer conversations or more questions',
  copyCodeSuccessToastTitle: 'Copied to clipboard',
  copyCodeButtonTooltip: 'Copy',
  copyCodeButtonSuccessTooltip: 'Copied',
  threadsSharedOnDate: 'shared on {0}',
  threadsMore: 'more',
  threadsExportPanelTitle: 'Select Format',
  threadsExportPanelAriaLabel: 'Select',
  threadsAADMSARedirectConfirm: 'Switch user configuration',
  threadsAADMSARedirectDescription: 'Your conversation history is being saved using a Microsoft account. The next time you log in with your personal account, it will show up here. ',
  threadsCancel: 'Cancel',
  threadsChatHistory: 'Chat history',
  threadsConfirm: 'Confirm',
  threadsDaysAgo: '{0} days ago',
  threadsDefaultChatName: 'Untitled chat',
  threadsDelete: 'Delete',
  threadsDescription: 'Bing, the AI-powered assistant, now auto-saves chats. You can access chats from any device, desktop, or mobile device and continue seamlessly. ',
  threadsDescriptionNote: 'Note that all chats will be automatically deleted within 90 days unless specifically saved. ',
  threadsEdit: 'Rename',
  threadsLoad: 'Load chat',
  threadsMinimizeRecent: 'Minimize recent chats',
  threadsMinimizeSaved: 'Minimize saved chats',
  threadsPreview: 'Preview',
  threadsPreviewText: 'Jump back to recent chats',
  threadsRecentTitle: 'Recent activity',
  threadsRecentTitleShort: 'Recently used',
  threadsSavedTitle: 'Saved',
  threadsSeeAllRecent: 'See all recent chats',
  threadsSeeAllSaved: 'View all saved chats',
  threadsTitle: 'Chat',
  threadsTitleForFlux: 'Menu',
  threadsYesterday: 'Yesterday',
  threads2TLastAccessed: 'Last answer time',
  threads2TInfoChanged: 'This information may have changed because of',
  threads2TArchivedText: 'Screenshot',
  threads2TReloadDescription: 'Click Reload to display the latest information from the web',
  threads2TFailedSearch: 'See the latest on Bing.com',
  threads2TReload: 'Search Bing.com',
  injectedActionCardTitle: 'Chat on this page?',
  injectedActionCardNewTopicTitle: 'Start a new chat about this page?',
  injectedActionCardConfirm: 'Send',
  injectedActionCardDeny: 'ignore',
  webPageContextPrefix:  'Website visited',
  useGPT4SwitchLabel:  'Use GPT-4',
  zeroInputSuggestionFallback1:  'Which coffee grinder has the best rating?',
  zeroInputSuggestionFallback2:  'What are the top three models for a family of six on a budget?',
  zeroInputSuggestionFallback3: 'Write a joke that my colleague would find funny',
  zeroInputSuggestionFallback4:  'Whats next? where should I shop to find it?',
  zeroInputSuggestionFallback5:  'Write an original fable about a fish and a frog finding love',
  zeroInputSuggestionFallback6: 'Create a table to help me plan my meals for the next two weeks',
  zeroInputSuggestionFallback7:  'Create a slogan for a new social media platform with a satirical twist',
  zeroInputSuggestionCategory1: 'store',
  zeroInputSuggestionCategory2: 'Compare',
  zeroInputSuggestionCategory3: 'laughing',
  zeroInputSuggestionCategory4: 'Chat',
  zeroInputSuggestionCategory5: 'write',
  zeroInputSuggestionCategory6: 'Organization',
  zeroInputSuggestionCategory7: 'Create',
  discoverMessageItemTitle: '📝 Rewrite the text together',
  discoverMessageItemContent: 'Try selecting text from the page to see what we can do together',
  pluginTitle: 'plugin',
  bookNowWithOpenTable:  'Book now with OpenTable',
  scrollLeft:  'Scroll left',
  scrollRight:  'Scroll right',
  personalizationConsentTitleText: 'Oh yes, do you want a personalized answer?✨ ',
  personalizationConsentContentText1: 'When you share your chat history, Bing tailors your response to you and your interests. ',
  personalizationConsentContentText2: '. ',
  personalizationConsentLearnMoreText: 'Learn more about personalized answers',
  personalizationConsentEnableText: 'Yes, I want it!',
  personalizationConsentAskAgainLaterText: 'I ll talk about it later',
  personalizationConsentDisableText: 'No, thank you',
  personalizationConsentStatusPositiveText: 'Personalization enabled. ',
  personalizationConsentStatusNegativeText: 'Personalization is not enabled. ',
  personalizationConsentSettingsText1: 'To modify, visit',
  personalizationConsentSettingsLinkText: 'Bing Chat Settings',
  personalizationConsentSettingsText2: 'Page',
  pluginEnabledPlugin: 'Enabled',
  pluginEnabledNumber: '{0} / {1}',
  pluginStartNewTopic: 'Start a new topic',
  pluginToChangePlugin: 'Change plugin',
  pluginNotificationMaxExceeded: 'Maximum number of plugins enabled',
  pluginNotificationExclusive: '{0} is too similar to {1}. Please select one',
  pluginTerms: 'Terms of Use',
  pluginPrivacy: 'Privacy Policy',
  pluginPanelFreTitle: 'Plugin is now available',
  pluginPanelFreTextLabel: 'New:',
  pluginPanelFreText: 'Opens the plugin to help you find restaurant reservations, flights, and more from your favorite brands. ',
  pluginPanelFreDismiss: 'ignore',
  pluginPanelAlertTitle: 'Plugin is not available in Balanced mode',
  pluginPanelAlertCta: 'Reset Conversation',
  pluginPanelAlertSubtitle: 'and use the "More creative" or "more precise" dialog style, then try again. ',
  pluginLimitationTitle: 'Use plugin with Bing AI',
  pluginLimitationMax: 'Select up to 3 plugins for any one conversation thread. ',
  pluginLimitationLock: 'The plugin locks into the dialog before selecting "New Theme" to make changes. ',
  pluginShowMore: 'Unfold',
  pluginPanelNolimit: 'Disabling {0} does not affect plugin limits',
  threadsToggleExpansion: 'Toggle expansion',
  threadsEnabledPlugins: 'Plugins enabled:',
  bingSearchDisabled: 'Bing is disabled. ',
  bingSearchDisabledforMessage: 'Bing is disabled',
  activateSearch: 'Start a new topic and activate search',
  visualSearchFlyoutTitle: 'Add image',
  visualSearchGenericErrorMessage: 'Failed to upload this file. Please try again. ',
  visualSearchUnsupportedFileMessage: 'This file type is not supported. Select the image file and try again. ',
  visualSearchInvalidUrlMessage: 'Sorry - the URL you provided doesnt seem to be valid. Please try again',
  visualSearchFlyoutInputboxAriaLabel: 'Paste image or link',
  visualSearchFlyoutTakePhotoButtonLabel: 'Take photo',
  visualSearchDragAndDropLabel: 'Drag image here',
  visualSearchFlyoutUploadButtonLabel:  'Upload from this device',
  raiDisclaimerLabel:  'AI-generated content may be incorrect', 
  slimHeaderTitle: 'See answers for new AI-powered Bing' ,
  starterPageTitle: 'Bing is an AI-powered online assistant' ,
  starterDescription: 'Chat with Bing in your own language. If you feel stuck, choose one of the following opening lines to see how Bing works: ',
  starterSubtitle1:  'Conversation',
  starterSubtitle2:  'Unleash your creativity',
  starterSubtitle3: 'Search smarter',
  starterContent1: 'Bing works best when using natural sentences like you would in everyday chat and asking for follow-up content',
  starterContent2: 'Whether its with images or text, Bing can spark your creativity by bringing your vision to life',
  starterContent3: 'Chatting with Bing is a new way to search. Let Bing aggregate web content and provide answers',
  starterChatQuery1:  'Do you think there is life on other planets?',
  starterChatQuery2:  'What happens if I have trouble sleeping, but it only happens in the summer?',
  starterChatQuery3:  'I want to start a garden, but I dont know anything about it. What do I need to do as a first step?',
  starterChatQuery4: 'Do you think a crocodile or a grizzly bear will win in a fight?',
  starterChatQuery5:  'Ive been reading a lot of non-fiction books lately. Can you help me find a fictional version of a theme I like?',
  starterChatQuery6:  'Lets have a conversation where everything you say is written in emojis. ',
  starterChatQuery7: 'Ive been thinking about moving to a new place. Where do you think I should go?',
  starterChatQuery8: 'I used to write in a journal, but lately ve been lazy a lot. How can I keep it in the habit?',
  starterChatQuery9: 'Do you dream like a human?',
  starterChatQuery10: 'Is it possible for an earthquake, a tsunami, and a volcanic eruption to occur at the same time?',
  starterCreateQuery1: 'I have a black puppy, except for the white fur on the belly. Please draw it as a cartoon character. ',
  starterCreateQuery2:  'Write a bedtime story for my 3-year-old niece. She loves horses and magic, and I think the story should rhyme "',
  starterCreateQuery3: 'Write a short essay in the tone of an arrogant professor to prove that the moon is better than the sun',
  starterCreateQuery4: 'Draw a polar bear basking on an iceberg in an impressionist style. It should also be drinking lemonade',
  starterCreateQuery5: 'Lets create a color and write a social media post to introduce it to the world',
  starterCreateQuery6: 'As Christian Bales Batman,please tell me how to deal with traffic on a motorcycle',
  starterCreateQuery7: 'Make a sales pitch for a new beer brand in the tone of a dad who brews at home and causes a small explosion',
  starterCreateQuery8: 'Design a poster for a café with a sunset and make the most of the space',
  starterCreateQuery9:  'Draw a giraffe as the captain of a barge on a lake',
  starterCreateQuery10:  'Write an introductory paragraph for an essay on the history of feminist literature and give me five writing prompts to continue',
  starterCompareQuery1: 'Find me a recipe for tiramisu, make a shopping list for me, and arrange it so I can quickly find the ingredients in the store',
  starterCompareQuery2:  'Provide me with todays local news debrief, excluding sports content',
  starterCompareQuery3:  'Summarize the latest  AI  research with five bullet points and draw conclusions about whats next',
  starterCompareQuery4: 'Create a table to compare the best electric vehicles by brand, price, safety features and possible add-ons',
  starterCompareQuery5: 'Where is the nearest park near here with a childrens playground?',
  starterCompareQuery6:  'Three wine suggestions for the Italian dishes I want to make in the evening. This dish is based on tomatoes and is a bit spicy. ',
  starterCompareQuery7: 'Give me a summary of the latest focus of UN',
  starterCompareQuery8: 'Create a table to compare unexpected Pulitzer Prize winners and why',
  starterCompareQuery9:  'Explain how the  Internet works in a way that your child can understand',
  starterCompareQuery10:  'Translate the poem Introduction to the poem into French and briefly explain the meaning of any loss in English',
  notificationMaxTurnsAndOpenEdge: 'You have reached the conversation limit. To continue chatting, ',
  notificationMaxTurnsAndOpenEdgeCta: 'Open in Microsoft Edge',
  actionBarPromptGuideToolTip: 'Prompt guide',
   actionBarAttachButtonToolTip: 'Attach',
  actionBarLongPlaceholder: 'Ask me anything or type/add people, files, etc.'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 设置未登录用户的 codexMUIDUser 为 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Bing Chat Enterprise'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = '由 AI 支持的适用于 Web 的 Copilot'
  _w['_sydConvTranslation']['inputRaiLabel'] = '你的个人和公司数据在此聊天中受到保护'
}