name: Bug Report
description: Submit a bug report
title: "[Bug] 🐛 "
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please describe briefly what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please describe how to reproduce this behavior, such as the order of operations.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please describe the expected behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Please provide relevant screenshots as detailed as possible, such as chat records, console logs, server logs, packet content, etc.
  - type: textarea
    attributes:
      label: Versions
      description: Please fill in the corresponding version numbers.
      value: |
        - OS: <!-- e.g. Windows 10 -->
        - Browser & Version: <!-- e.g. Chrome 115 -->
        - GoProxiBing Version: <!-- e.g. 1.9.0 -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Please describe any additional information you want to add.
