name: Feature Request
description: Submit a feature request
title: "[Feature] 🌈 "
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Describe the problem related to the feature request
      description: Please briefly explain what problem led you to want a new feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: Please explain what kind of method (such as adding what function) you would like to use to solve the above problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: In addition to the above method, what other implementations have you considered?
  - type: textarea
    attributes:
      label: Additional context
      description: Please describe any additional information you want to add.
